<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Proto\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.account.AccountLoginResponse</code>
 */
class AccountLoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 openid = 1;</code>
     */
    private $openid = 0;
    /**
     * <code>int32 sid = 2;</code>
     */
    private $sid = 0;
    /**
     * <code>repeated .proto.playerinfo.BasePlayerInfo roles = 3;</code>
     */
    private $roles;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 openid = 1;</code>
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * <code>int64 openid = 1;</code>
     */
    public function setOpenid($var)
    {
        GPBUtil::checkInt64($var);
        $this->openid = $var;
    }

    /**
     * <code>int32 sid = 2;</code>
     */
    public function getSid()
    {
        return $this->sid;
    }

    /**
     * <code>int32 sid = 2;</code>
     */
    public function setSid($var)
    {
        GPBUtil::checkInt32($var);
        $this->sid = $var;
    }

    /**
     * <code>repeated .proto.playerinfo.BasePlayerInfo roles = 3;</code>
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * <code>repeated .proto.playerinfo.BasePlayerInfo roles = 3;</code>
     */
    public function setRoles(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Playerinfo\BasePlayerInfo::class);
        $this->roles = $var;
    }

}

