<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errornumber.proto

/**
 * Protobuf enum <code>proto.errornumber.ErrorNumber</code>
 */
namespace Proto\Errornumber;

class ErrorNumber
{
    /**
     * <code>EC_SUCCESS = 0;</code>
     */
    const EC_SUCCESS = 0;
    /**
     * <pre>
     * 数据错误
     * </pre>
     *
     * <code>EC_DATA_ERROR = 1;</code>
     */
    const EC_DATA_ERROR = 1;
    /**
     * <pre>
     * 非法请求
     * </pre>
     *
     * <code>EC_INVALID_REQUEST = 2;</code>
     */
    const EC_INVALID_REQUEST = 2;
    /**
     * <pre>
     * 配置错误
     * </pre>
     *
     * <code>EC_CONFIG_ERROR = 3;</code>
     */
    const EC_CONFIG_ERROR = 3;
    /**
     * <pre>
     * 功能未开启
     * </pre>
     *
     * <code>EC_MODULE_NOT_AVAILABLE = 50;</code>
     */
    const EC_MODULE_NOT_AVAILABLE = 50;
    /**
     * <pre>
     * 登录相关错误码
     * </pre>
     *
     * <code>EC_TOKEN_INVALID = 100;</code>
     */
    const EC_TOKEN_INVALID = 100;
    /**
     * <pre>
     * TOKEN过期
     * </pre>
     *
     * <code>EC_TOKEN_EXPIRED = 101;</code>
     */
    const EC_TOKEN_EXPIRED = 101;
    /**
     * <pre>
     * 另外一个登录了, 被挤下线
     * </pre>
     *
     * <code>EC_KICK_ON_ANOTHER_LOGIN = 102;</code>
     */
    const EC_KICK_ON_ANOTHER_LOGIN = 102;
    /**
     * <pre>
     * 职业ID不合法
     * </pre>
     *
     * <code>EC_CREATE_ROLE_PROFESSION_ERROR = 103;</code>
     */
    const EC_CREATE_ROLE_PROFESSION_ERROR = 103;
    /**
     * <pre>
     * 名字重复
     * </pre>
     *
     * <code>EC_CREATE_PLAYER_DUPLICATE_NAME = 104;</code>
     */
    const EC_CREATE_PLAYER_DUPLICATE_NAME = 104;
    /**
     * <pre>
     * 名字非法
     * </pre>
     *
     * <code>EC_CREATE_PLAYER_ILLEGAL_NAME = 105;</code>
     */
    const EC_CREATE_PLAYER_ILLEGAL_NAME = 105;
    /**
     * <pre>
     * 名字太短
     * </pre>
     *
     * <code>EC_CREATE_PLAYER_NAME_TOO_SHORT = 106;</code>
     */
    const EC_CREATE_PLAYER_NAME_TOO_SHORT = 106;
    /**
     * <pre>
     * 名字太长
     * </pre>
     *
     * <code>EC_CREATE_PLAYER_NAME_TOO_LONG = 107;</code>
     */
    const EC_CREATE_PLAYER_NAME_TOO_LONG = 107;
    /**
     * <pre>
     * 玩家被禁止登陆
     * </pre>
     *
     * <code>EC_PLAYER_BANNED = 108;</code>
     */
    const EC_PLAYER_BANNED = 108;
    /**
     * <pre>
     * 玩家登陆失败
     * </pre>
     *
     * <code>EC_ACCOUNT_LOGIN_FAILED = 109;</code>
     */
    const EC_ACCOUNT_LOGIN_FAILED = 109;
    /**
     * <pre>
     * 登录服务器未能解析
     * </pre>
     *
     * <code>EC_LOGIN_SERVER_RESOLVE_FAILED = 110;</code>
     */
    const EC_LOGIN_SERVER_RESOLVE_FAILED = 110;
    /**
     * <pre>
     * 登录服务器连接失败
     * </pre>
     *
     * <code>EC_LOGIN_SERVER_CONN_FAILED = 111;</code>
     */
    const EC_LOGIN_SERVER_CONN_FAILED = 111;
    /**
     * <pre>
     * 登录服务器验证超时
     * </pre>
     *
     * <code>EC_LOGIN_SERVER_VERIFY_TIMEOUT = 112;</code>
     */
    const EC_LOGIN_SERVER_VERIFY_TIMEOUT = 112;
    /**
     * <pre>
     * 角色已创建
     * </pre>
     *
     * <code>EC_PLAYER_CREATED = 113;</code>
     */
    const EC_PLAYER_CREATED = 113;
    /**
     * <pre>
     * 重练失败，需重新登录
     * </pre>
     *
     * <code>EC_RECONNECT_PLAYER_NOT_EXIST = 114;</code>
     */
    const EC_RECONNECT_PLAYER_NOT_EXIST = 114;
    /**
     * <pre>
     * 角色创建失败
     * </pre>
     *
     * <code>EC_PLAYER_CREATED_FAILED = 115;</code>
     */
    const EC_PLAYER_CREATED_FAILED = 115;
    /**
     * <pre>
     * 角色切换失败，需重新登录
     * </pre>
     *
     * <code>EC_SWITCH_ROLE_INVALID_REQUEST = 116;</code>
     */
    const EC_SWITCH_ROLE_INVALID_REQUEST = 116;
    /**
     * <pre>
     * GM后台踢下线
     * </pre>
     *
     * <code>EC_KICK_ON_GM = 117;</code>
     */
    const EC_KICK_ON_GM = 117;
    /**
     * <pre>
     * 金钱相关错误码
     * </pre>
     *
     * <code>EC_MONEY_INVALID_TYPE = 120;</code>
     */
    const EC_MONEY_INVALID_TYPE = 120;
    /**
     * <pre>
     * 增减MONEY时候， 数值为负数
     * </pre>
     *
     * <code>EC_MONEY_NAGITIVE_NUM = 121;</code>
     */
    const EC_MONEY_NAGITIVE_NUM = 121;
    /**
     * <pre>
     * 没有足够的消耗物品
     * </pre>
     *
     * <code>EC_NOT_ENOUGH_ITEM = 122;</code>
     */
    const EC_NOT_ENOUGH_ITEM = 122;
    /**
     * <pre>
     * 金币不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_COIN = 130;</code>
     */
    const EC_MONEY_NOT_ENOUGH_COIN = 130;
    /**
     * <pre>
     * 元宝不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_YUANBAO = 131;</code>
     */
    const EC_MONEY_NOT_ENOUGH_YUANBAO = 131;
    /**
     * <pre>
     * 礼券不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_LIQUAN = 132;</code>
     */
    const EC_MONEY_NOT_ENOUGH_LIQUAN = 132;
    /**
     * <pre>
     * 体力不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_SPIRIT = 133;</code>
     */
    const EC_MONEY_NOT_ENOUGH_SPIRIT = 133;
    /**
     * <pre>
     * 魂力不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_HUNLI = 134;</code>
     */
    const EC_MONEY_NOT_ENOUGH_HUNLI = 134;
    /**
     * <pre>
     * 经验不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_EXP = 135;</code>
     */
    const EC_MONEY_NOT_ENOUGH_EXP = 135;
    /**
     * <pre>
     * 荣誉不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_HONOUR = 136;</code>
     */
    const EC_MONEY_NOT_ENOUGH_HONOUR = 136;
    /**
     * <pre>
     * 公会贡献不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_GUILD_CONTRIBUTION = 138;</code>
     */
    const EC_MONEY_NOT_ENOUGH_GUILD_CONTRIBUTION = 138;
    /**
     * <pre>
     * 占用到159， 预留30个exchange类型
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH_MONEY29 = 159;</code>
     */
    const EC_MONEY_NOT_ENOUGH_MONEY29 = 159;
    /**
     * <pre>
     * 货币不够
     * </pre>
     *
     * <code>EC_MONEY_NOT_ENOUGH = 160;</code>
     */
    const EC_MONEY_NOT_ENOUGH = 160;
    /**
     * <pre>
     * 等级达到满级
     * </pre>
     *
     * <code>EC_LEVEL_REACH_MAX_VALUE = 170;</code>
     */
    const EC_LEVEL_REACH_MAX_VALUE = 170;
    /**
     * <pre>
     ***血统错误码**
     * </pre>
     *
     * <code>EC_ANCESTRY_UNLOCK_ANCE_EXIST = 200;</code>
     */
    const EC_ANCESTRY_UNLOCK_ANCE_EXIST = 200;
    /**
     * <pre>
     * 该解锁血统不存在
     * </pre>
     *
     * <code>EC_ANCESTRY_UNLOCK_ANCE_ID_ERROR = 201;</code>
     */
    const EC_ANCESTRY_UNLOCK_ANCE_ID_ERROR = 201;
    /**
     * <pre>
     * 玩家等级不足
     * </pre>
     *
     * <code>EC_ANCESTRY_UNLOCK_PLAYERLEVEL = 202;</code>
     */
    const EC_ANCESTRY_UNLOCK_PLAYERLEVEL = 202;
    /**
     * <pre>
     * 前置血统未解锁
     * </pre>
     *
     * <code>EC_ANCESTRY_UNLOCK_PRENOTEXIST = 203;</code>
     */
    const EC_ANCESTRY_UNLOCK_PRENOTEXIST = 203;
    /**
     * <pre>
     * 前置血统等级不足
     * </pre>
     *
     * <code>EC_ANCESTRY_UNLOCK_PRELEVEL = 204;</code>
     */
    const EC_ANCESTRY_UNLOCK_PRELEVEL = 204;
    /**
     * <pre>
     * 激活血统未解锁
     * </pre>
     *
     * <code>EC_ANCESTRY_ACTIVATE_ANCE_UNLOCK = 205;</code>
     */
    const EC_ANCESTRY_ACTIVATE_ANCE_UNLOCK = 205;
    /**
     * <pre>
     * 升级血统未解锁
     * </pre>
     *
     * <code>EC_ANCESTRY_UPGRADE_ANCE_UNLOCK = 206;</code>
     */
    const EC_ANCESTRY_UPGRADE_ANCE_UNLOCK = 206;
    /**
     * <pre>
     * 血统操作类别不合法
     * </pre>
     *
     * <code>EC_ANCESTRY_OPERATE_TYPE_ERROR = 207;</code>
     */
    const EC_ANCESTRY_OPERATE_TYPE_ERROR = 207;
    /**
     * <pre>
     * 解锁血统需要材料不足
     * </pre>
     *
     * <code>EC_ANCESTRY_UNLOCK_MATERIAL_NOT_ENOUGH = 208;</code>
     */
    const EC_ANCESTRY_UNLOCK_MATERIAL_NOT_ENOUGH = 208;
    /**
     * <pre>
     * 血统还未解锁
     * </pre>
     *
     * <code>EC_ANCESTRY_NOT_UNLOCK = 209;</code>
     */
    const EC_ANCESTRY_NOT_UNLOCK = 209;
    /**
     * <pre>
     * 血统技能已经在使用
     * </pre>
     *
     * <code>EC_ANCESTRY_SKILL_ALREADRY_INUSE = 210;</code>
     */
    const EC_ANCESTRY_SKILL_ALREADRY_INUSE = 210;
    /**
     * <pre>
     * 血统技能没在使用
     * </pre>
     *
     * <code>EC_ANCESTRY_SKILL_NOT_INUSE = 211;</code>
     */
    const EC_ANCESTRY_SKILL_NOT_INUSE = 211;
    /**
     * <pre>
     * 血统已经满级
     * </pre>
     *
     * <code>EC_ANCESTRY_UPGRADE_FULL_LEVEL = 212;</code>
     */
    const EC_ANCESTRY_UPGRADE_FULL_LEVEL = 212;
    /**
     * <pre>
     * 血统技能个数已满
     * </pre>
     *
     * <code>EC_ANCESTRY_SKILL_NUM_FULL = 213;</code>
     */
    const EC_ANCESTRY_SKILL_NUM_FULL = 213;
    /**
     * <pre>
     * 血统技能掌控力已满
     * </pre>
     *
     * <code>EC_ANCESTRY_SKILL_CONTROL_FULL = 214;</code>
     */
    const EC_ANCESTRY_SKILL_CONTROL_FULL = 214;
    /**
     * <pre>
     * 血统技能无效
     * </pre>
     *
     * <code>EC_ANCESTRY_ID_NOT_VALID = 215;</code>
     */
    const EC_ANCESTRY_ID_NOT_VALID = 215;
    /**
     * <pre>
     * 升级血统需要材料不足
     * </pre>
     *
     * <code>EC_ANCESTRY_UPGRADE_MATERIAL_NOT_ENOUGH = 216;</code>
     */
    const EC_ANCESTRY_UPGRADE_MATERIAL_NOT_ENOUGH = 216;
    /**
     * <pre>
     * 血统等级不足
     * </pre>
     *
     * <code>EC_ANCESTRY_LEVEL_NOT_ENOUGH = 217;</code>
     */
    const EC_ANCESTRY_LEVEL_NOT_ENOUGH = 217;
    /**
     * <pre>
     ******培养错误码*****
     * </pre>
     *
     * <code>EC_TRAIN_RANGE_NOT_EXIST = 301;</code>
     */
    const EC_TRAIN_RANGE_NOT_EXIST = 301;
    /**
     * <pre>
     * 灵魂培养道具不足
     * </pre>
     *
     * <code>EC_TRAIN_SOUL_PROP_NOT_ENOUGH = 302;</code>
     */
    const EC_TRAIN_SOUL_PROP_NOT_ENOUGH = 302;
    /**
     * <pre>
     * 龙魂培养元宝不足
     * </pre>
     *
     * <code>EC_TRAIN_GRAGON_YUANBAO_NOT_ENOUGH = 303;</code>
     */
    const EC_TRAIN_GRAGON_YUANBAO_NOT_ENOUGH = 303;
    /**
     * <pre>
     * 培养所需材料不足
     * </pre>
     *
     * <code>EC_CONSUME_MATERIAL_NOT_ENOUGH = 304;</code>
     */
    const EC_CONSUME_MATERIAL_NOT_ENOUGH = 304;
    /**
     * <pre>
     ******转职进阶错误码****
     * </pre>
     *
     * <code>EC_TRANSFER_PROFESS_ID_ERROR = 401;</code>
     */
    const EC_TRANSFER_PROFESS_ID_ERROR = 401;
    /**
     * <pre>
     * 转职所需等级不足
     * </pre>
     *
     * <code>EC_TRANSFER_PROFESS_LEVEL_RANGE = 402;</code>
     */
    const EC_TRANSFER_PROFESS_LEVEL_RANGE = 402;
    /**
     * <pre>
     ******背包操作错误码******
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_TYPE_ERROR = 501;</code>
     */
    const EC_BAG_OPERATE_BAG_TYPE_ERROR = 501;
    /**
     * <pre>
     * 扣除道具数量超过限制
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_ITEM_NUM_ERROR = 502;</code>
     */
    const EC_BAG_OPERATE_BAG_ITEM_NUM_ERROR = 502;
    /**
     * <pre>
     * 玩家道具数量不足
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_ITEM_NUM_NOT_ENOUGH = 503;</code>
     */
    const EC_BAG_OPERATE_BAG_ITEM_NUM_NOT_ENOUGH = 503;
    /**
     * <pre>
     * 道具id不合法
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_ITEM_TID_ERROR = 504;</code>
     */
    const EC_BAG_OPERATE_BAG_ITEM_TID_ERROR = 504;
    /**
     * <pre>
     * 不存在该道具ID
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_NOT_EXIST_ITEM_ID = 505;</code>
     */
    const EC_BAG_OPERATE_BAG_NOT_EXIST_ITEM_ID = 505;
    /**
     * <pre>
     * 道具添加失败
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_ADD_ITEM_FAILED = 506;</code>
     */
    const EC_BAG_OPERATE_BAG_ADD_ITEM_FAILED = 506;
    /**
     * <pre>
     * 道具扣除失败
     * </pre>
     *
     * <code>EC_BAG_OPERATE_BAG_COST_ITEM_FAILED = 507;</code>
     */
    const EC_BAG_OPERATE_BAG_COST_ITEM_FAILED = 507;
    /**
     * <pre>
     * 背包满
     * </pre>
     *
     * <code>EC_BAG_IS_FULL = 508;</code>
     */
    const EC_BAG_IS_FULL = 508;
    /**
     * <pre>
     * 背包空间不足
     * </pre>
     *
     * <code>EC_BAG_SIZE_NOT_ENOUGH = 509;</code>
     */
    const EC_BAG_SIZE_NOT_ENOUGH = 509;
    /**
     * <pre>
     * 该装备处于装备状态，不能删除
     * </pre>
     *
     * <code>EC_BAG_OPERATE_EQUIP_CAN_NOT_DELETE = 510;</code>
     */
    const EC_BAG_OPERATE_EQUIP_CAN_NOT_DELETE = 510;
    /**
     * <pre>
     * 处于锁定状态的槽位数量不足
     * </pre>
     *
     * <code>EC_BAG_SLOT_LOCKED_SLOT_NOT_ENOUGH = 511;</code>
     */
    const EC_BAG_SLOT_LOCKED_SLOT_NOT_ENOUGH = 511;
    /**
     * <pre>
     * 临时背包非空
     * </pre>
     *
     * <code>EC_BAG_TMEP_BAG_NOT_EMPTY = 512;</code>
     */
    const EC_BAG_TMEP_BAG_NOT_EMPTY = 512;
    /**
     * <pre>
     * 没有找到该装备, 可能已经销魂
     * </pre>
     *
     * <code>EC_NOT_FOUND_ITEM = 513;</code>
     */
    const EC_NOT_FOUND_ITEM = 513;
    /**
     * <pre>
     * 该物品不可出售
     * </pre>
     *
     * <code>EC_ITEM_CAN_NOT_SALE = 514;</code>
     */
    const EC_ITEM_CAN_NOT_SALE = 514;
    /**
     * <pre>
     * 圣器已存在
     * </pre>
     *
     * <code>EC_RECLIS_EXIST = 515;</code>
     */
    const EC_RECLIS_EXIST = 515;
    /**
     * <pre>
     * 该物品不存在
     * </pre>
     *
     * <code>EC_BAG_ITEMS_NOT_EXIST = 516;</code>
     */
    const EC_BAG_ITEMS_NOT_EXIST = 516;
    /**
     * <pre>
     ******装备锻炼错误码*****
     * </pre>
     *
     * <code>EC_EQUIP_DEFAULT = 600;</code>
     */
    const EC_EQUIP_DEFAULT = 600;
    /**
     * <code>EC_EQUIP_NOT_EXIST = 601;</code>
     */
    const EC_EQUIP_NOT_EXIST = 601;
    /**
     * <code>EC_EQUIP_MATERIAL_NOT_ENOUGH = 602;</code>
     */
    const EC_EQUIP_MATERIAL_NOT_ENOUGH = 602;
    /**
     * <code>EC_EQUIP_COIN_NOT_ENOUGH = 603;</code>
     */
    const EC_EQUIP_COIN_NOT_ENOUGH = 603;
    /**
     * <code>EC_EQUIP_YUANBAO_NOT_ENOUGH = 604;</code>
     */
    const EC_EQUIP_YUANBAO_NOT_ENOUGH = 604;
    /**
     * <code>EC_EQUIP_SOCKET_NOT_ENOUGH = 605;</code>
     */
    const EC_EQUIP_SOCKET_NOT_ENOUGH = 605;
    /**
     * <code>EC_EQUIP_ENHANT_LEVEL_NOT_ENOUGH = 606;</code>
     */
    const EC_EQUIP_ENHANT_LEVEL_NOT_ENOUGH = 606;
    /**
     * <pre>
     * 物品已经装备
     * </pre>
     *
     * <code>EC_EQUIP_ALREADY_EQUIPED = 607;</code>
     */
    const EC_EQUIP_ALREADY_EQUIPED = 607;
    /**
     * <code>EC_EQUIP_ENHANT_TYPE_NOT_MATCH = 608;</code>
     */
    const EC_EQUIP_ENHANT_TYPE_NOT_MATCH = 608;
    /**
     * <pre>
     * 装备类型与职业不符
     * </pre>
     *
     * <code>EC_EQUIP_TYPE_NOT_MATCH = 609;</code>
     */
    const EC_EQUIP_TYPE_NOT_MATCH = 609;
    /**
     * <pre>
     * 装备类型与职业不符,职业特别限制
     * </pre>
     *
     * <code>EC_EQUIP_TYPE_NOT_MATCH_PRO_LIMIT = 610;</code>
     */
    const EC_EQUIP_TYPE_NOT_MATCH_PRO_LIMIT = 610;
    /**
     * <code>EC_EQUIP_LEVEL_NOT_REACH = 611;</code>
     */
    const EC_EQUIP_LEVEL_NOT_REACH = 611;
    /**
     * <code>EC_EQUIP_HAS_REACH_TOP_LEVEL = 612;</code>
     */
    const EC_EQUIP_HAS_REACH_TOP_LEVEL = 612;
    /**
     * <code>EC_EQUIP_CAN_NOT_OPEN_SOCKET = 613;</code>
     */
    const EC_EQUIP_CAN_NOT_OPEN_SOCKET = 613;
    /**
     * <code>EC_EQUIP_INLAY_GEM_TEMPLATE_NOT_EXIST = 614;</code>
     */
    const EC_EQUIP_INLAY_GEM_TEMPLATE_NOT_EXIST = 614;
    /**
     * <code>EC_EQUIP_INLAY_GEM_TYPE_NOT_MATCH = 615;</code>
     */
    const EC_EQUIP_INLAY_GEM_TYPE_NOT_MATCH = 615;
    /**
     * <pre>
     * 该孔位不可镶嵌
     * </pre>
     *
     * <code>EC_EQUIP_INLAY_SOCKET_INDEX_INVALID = 616;</code>
     */
    const EC_EQUIP_INLAY_SOCKET_INDEX_INVALID = 616;
    /**
     * <code>EC_EQUIP_STRENGHTEN_PROTECT_MATERIAL_NOT_ENOUGH = 617;</code>
     */
    const EC_EQUIP_STRENGHTEN_PROTECT_MATERIAL_NOT_ENOUGH = 617;
    /**
     * <pre>
     * 该孔不可拆除
     * </pre>
     *
     * <code>EC_EQUIP_UNINLAY_SOCKET_INDEX_INVALID = 618;</code>
     */
    const EC_EQUIP_UNINLAY_SOCKET_INDEX_INVALID = 618;
    /**
     * <pre>
     * 永久性装备不可以拆卸
     * </pre>
     *
     * <code>EC_PERPETUAL_EQUIP_CAN_NOT_UNEQUIP = 619;</code>
     */
    const EC_PERPETUAL_EQUIP_CAN_NOT_UNEQUIP = 619;
    /**
     * <pre>
     * 装备属性强化到最大等级
     * </pre>
     *
     * <code>EC_EQUIP_STRENGTH_OF_ATTRIBUTE_REACH_TOP_LEVEL = 620;</code>
     */
    const EC_EQUIP_STRENGTH_OF_ATTRIBUTE_REACH_TOP_LEVEL = 620;
    /**
     * <pre>
     * 玩家等级不足
     * </pre>
     *
     * <code>EC_EQUIP_PLAYER_LEVEL_LIMITED = 621;</code>
     */
    const EC_EQUIP_PLAYER_LEVEL_LIMITED = 621;
    /**
     * <pre>
     * 玩家vip等级不足
     * </pre>
     *
     * <code>EC_EQUIP_PLAYER_VIP_LEVEL_LIMITED = 622;</code>
     */
    const EC_EQUIP_PLAYER_VIP_LEVEL_LIMITED = 622;
    /**
     * <pre>
     * 不能装备相同的特殊装备
     * </pre>
     *
     * <code>EC_EQUIP_NOT_EQUIP_THE_SAME_PERPETUAL_EQUPMENT = 623;</code>
     */
    const EC_EQUIP_NOT_EQUIP_THE_SAME_PERPETUAL_EQUPMENT = 623;
    /**
     * <pre>
     * 强化等级未达到指定等级
     * </pre>
     *
     * <code>EC_EQUIP_STRENGTH_LEVEL_NOT_REACH = 624;</code>
     */
    const EC_EQUIP_STRENGTH_LEVEL_NOT_REACH = 624;
    /**
     * <pre>
     * 强化等级不能超过角色等级
     * </pre>
     *
     * <code>EC_EQUIP_STRENGTH_LEVEL_NO_MORE_THAN_PLAYER_LEVEL = 625;</code>
     */
    const EC_EQUIP_STRENGTH_LEVEL_NO_MORE_THAN_PLAYER_LEVEL = 625;
    /**
     * <pre>
     * 该类型圣器不可被吞噬
     * </pre>
     *
     * <code>EC_EQUIP_RECLIS_CAN_NOT_BE_SWALLOW = 626;</code>
     */
    const EC_EQUIP_RECLIS_CAN_NOT_BE_SWALLOW = 626;
    /**
     * <pre>
     * 圣器强化吞噬物品不足
     * </pre>
     *
     * <code>EC_EQUIP_RECLIS_SWALLOW_ITEMS_NOT_ENOUGH = 627;</code>
     */
    const EC_EQUIP_RECLIS_SWALLOW_ITEMS_NOT_ENOUGH = 627;
    /**
     * <pre>
     * 圣器强化所选材料类型非法
     * </pre>
     *
     * <code>EC_EQUIP_RECLIS_SWALLOW_ITEMS_UNVALID = 628;</code>
     */
    const EC_EQUIP_RECLIS_SWALLOW_ITEMS_UNVALID = 628;
    /**
     * <pre>
     * 圣器已达最大阶级
     * </pre>
     *
     * <code>EC_RELICS_MAX_CLASS_LIMIT = 629;</code>
     */
    const EC_RELICS_MAX_CLASS_LIMIT = 629;
    /**
     * <pre>
     ****** 商城操作错误码 *****
     * </pre>
     *
     * <code>EC_MALL_ACTIVITY_OUT_TIME = 701;</code>
     */
    const EC_MALL_ACTIVITY_OUT_TIME = 701;
    /**
     * <pre>
     * 商品已售完
     * </pre>
     *
     * <code>EC_MALL_ACTIVITY_SELL_OUT = 702;</code>
     */
    const EC_MALL_ACTIVITY_SELL_OUT = 702;
    /**
     * <pre>
     ****** 技能操作错误码 *****
     * </pre>
     *
     * <code>EC_SKILL_PRE_SKILL_NOT_UNLOCK = 703;</code>
     */
    const EC_SKILL_PRE_SKILL_NOT_UNLOCK = 703;
    /**
     * <pre>
     * 前置技能等级未达到
     * </pre>
     *
     * <code>EC_SKILL_PRE_SKILL_LEV_NOT_ENOUGH = 704;</code>
     */
    const EC_SKILL_PRE_SKILL_LEV_NOT_ENOUGH = 704;
    /**
     * <pre>
     * 技能解锁-玩家等级不足
     * </pre>
     *
     * <code>EC_SKILL_PLAYER_LEV_NOT_ENOUGH = 705;</code>
     */
    const EC_SKILL_PLAYER_LEV_NOT_ENOUGH = 705;
    /**
     * <pre>
     * 该技能已经解锁
     * </pre>
     *
     * <code>EC_SKILL_SKILL_UNLOCKED = 706;</code>
     */
    const EC_SKILL_SKILL_UNLOCKED = 706;
    /**
     * <pre>
     * 该种技能不能升级
     * </pre>
     *
     * <code>EC_SKILL_UPGRADE_SKILL_TYPE_ERROR = 707;</code>
     */
    const EC_SKILL_UPGRADE_SKILL_TYPE_ERROR = 707;
    /**
     * <pre>
     * 道具消耗不足
     * </pre>
     *
     * <code>EC_SKILL_CONSUME_ITEM_NOT_ENOUGH = 708;</code>
     */
    const EC_SKILL_CONSUME_ITEM_NOT_ENOUGH = 708;
    /**
     * <pre>
     * 该技能已经激活
     * </pre>
     *
     * <code>EC_SKILL_SKILL_ACTIVATED = 709;</code>
     */
    const EC_SKILL_SKILL_ACTIVATED = 709;
    /**
     * <pre>
     * 所属主动技能未解锁
     * </pre>
     *
     * <code>EC_SKILL_ININIAL_SKILL_LOCK = 710;</code>
     */
    const EC_SKILL_ININIAL_SKILL_LOCK = 710;
    /**
     * <pre>
     * 技能达到满级
     * </pre>
     *
     * <code>EC_SKILL_REACH_MAX_LEVEL = 711;</code>
     */
    const EC_SKILL_REACH_MAX_LEVEL = 711;
    /**
     * <pre>
     * 解锁技能职业不符
     * </pre>
     *
     * <code>EC_SKILL_UNLOCK_PROFESSION_ERROR = 712;</code>
     */
    const EC_SKILL_UNLOCK_PROFESSION_ERROR = 712;
    /**
     * <pre>
     * 解锁技能个数达最大值
     * </pre>
     *
     * <code>EC_SKILL_UNLOCK_NUMBER_OUT_RANGE = 713;</code>
     */
    const EC_SKILL_UNLOCK_NUMBER_OUT_RANGE = 713;
    /**
     * <pre>
     * 技能未解锁，不能升级
     * </pre>
     *
     * <code>EC_SKILL_LOCKED_UNABLE_UPGRADE = 714;</code>
     */
    const EC_SKILL_LOCKED_UNABLE_UPGRADE = 714;
    /**
     * <pre>
     * 主动技能未激活
     * </pre>
     *
     * <code>EC_SKILL_INITIAL_SKILL_UNACTIVATE = 715;</code>
     */
    const EC_SKILL_INITIAL_SKILL_UNACTIVATE = 715;
    /**
     * <pre>
     * 技能升级 - 主角等级不足
     * </pre>
     *
     * <code>EC_SKILL_UPGRADE_ROLE_LEVEL_LIMIT = 716;</code>
     */
    const EC_SKILL_UPGRADE_ROLE_LEVEL_LIMIT = 716;
    /**
     * <pre>
     ******血战buffer错误码*****
     * </pre>
     *
     * <code>EC_XUEZHAN_DEFAULT = 800;</code>
     */
    const EC_XUEZHAN_DEFAULT = 800;
    /**
     * <code>EC_XUEZHAN_BUFFER_NOT_EXIST = 801;</code>
     */
    const EC_XUEZHAN_BUFFER_NOT_EXIST = 801;
    /**
     * <code>EC_XUEZHAN_BUFFER_MATERIAL_NOT_ENOUGH = 802;</code>
     */
    const EC_XUEZHAN_BUFFER_MATERIAL_NOT_ENOUGH = 802;
    /**
     * <pre>
     ******合成物品错误码*****
     * </pre>
     *
     * <code>EC_COMPOSE_DEFAULT = 900;</code>
     */
    const EC_COMPOSE_DEFAULT = 900;
    /**
     * <pre>
     * 合成需要的材料不足
     * </pre>
     *
     * <code>EC_COMPOSE_MATERIAL_NOT_ENOUGH = 901;</code>
     */
    const EC_COMPOSE_MATERIAL_NOT_ENOUGH = 901;
    /**
     * <pre>
     * 合成需要背包空间不足
     * </pre>
     *
     * <code>EC_COMPOSE_POS_NOT_ENOUGH = 902;</code>
     */
    const EC_COMPOSE_POS_NOT_ENOUGH = 902;
    /**
     * <pre>
     ****** 角色相关错误码 ********
     * </pre>
     *
     * <code>EC_PLAYER_LEVEL_LIMIT = 1003;</code>
     */
    const EC_PLAYER_LEVEL_LIMIT = 1003;
    /**
     * <pre>
     * 玩家vip等级不够, 不能使用功能
     * </pre>
     *
     * <code>EC_PLAYER_VIP_LEVEL_LIMIT = 1004;</code>
     */
    const EC_PLAYER_VIP_LEVEL_LIMIT = 1004;
    /**
     * <pre>
     * 玩家 限制次数用光
     * </pre>
     *
     * <code>EC_LIMIT_COUNT_REACH_MAX = 1005;</code>
     */
    const EC_LIMIT_COUNT_REACH_MAX = 1005;
    /**
     * <pre>
     * 玩家不能转职, 任务没有完成
     * </pre>
     *
     * <code>EC_PROFESSION_UPGRADE_1_FLAG_NOT_OPEN = 1006;</code>
     */
    const EC_PROFESSION_UPGRADE_1_FLAG_NOT_OPEN = 1006;
    /**
     * <pre>
     * 玩家不能进阶, 任务没有完成
     * </pre>
     *
     * <code>EC_PROFESSION_UPGRADE_2_FLAG_NOT_OPEN = 1007;</code>
     */
    const EC_PROFESSION_UPGRADE_2_FLAG_NOT_OPEN = 1007;
    /**
     * <pre>
     * 没有找到玩家
     * </pre>
     *
     * <code>EC_NOT_FOUND_PLAYER = 1008;</code>
     */
    const EC_NOT_FOUND_PLAYER = 1008;
    /**
     * <pre>
     * 还在冷却中
     * </pre>
     *
     * <code>EC_STILL_ON_COOLDOWN = 1009;</code>
     */
    const EC_STILL_ON_COOLDOWN = 1009;
    /**
     * <pre>
     ****** 道具使用 相关错误码 ********
     * </pre>
     *
     * <code>EC_USEPROP_DEFAULT = 1100;</code>
     */
    const EC_USEPROP_DEFAULT = 1100;
    /**
     * <code>EC_USEPROP_NOT_EXIST = 1101;</code>
     */
    const EC_USEPROP_NOT_EXIST = 1101;
    /**
     * <code>EC_USEPROP_TEMPLATE_NOT_EXIST = 1102;</code>
     */
    const EC_USEPROP_TEMPLATE_NOT_EXIST = 1102;
    /**
     * <code>EC_USEPROP_TYPE_NOT_PROP = 1103;</code>
     */
    const EC_USEPROP_TYPE_NOT_PROP = 1103;
    /**
     * <code>EC_USEPROP_ADD_HP_ERR = 1104;</code>
     */
    const EC_USEPROP_ADD_HP_ERR = 1104;
    /**
     * <code>EC_USEPROP_ADD_SPIRIT_ERR = 1105;</code>
     */
    const EC_USEPROP_ADD_SPIRIT_ERR = 1105;
    /**
     * <code>EC_USEPROP_EAT_DRUG_ERR = 1106;</code>
     */
    const EC_USEPROP_EAT_DRUG_ERR = 1106;
    /**
     * <code>EC_USEPROP_ADD_BUFFER = 1107;</code>
     */
    const EC_USEPROP_ADD_BUFFER = 1107;
    /**
     * <code>EC_USEPROP_ADD_HUNLI_ERR = 1108;</code>
     */
    const EC_USEPROP_ADD_HUNLI_ERR = 1108;
    /**
     * <pre>
     ******* 连续登陆礼包 *******
     * </pre>
     *
     * <code>EC_CONTINUE_LOGIN_PRIZE_DAYS_NOT_ENOUGH = 1200;</code>
     */
    const EC_CONTINUE_LOGIN_PRIZE_DAYS_NOT_ENOUGH = 1200;
    /**
     * <pre>
     * 连续登陆礼包已领取
     * </pre>
     *
     * <code>EC_CONTINUE_LOGIN_PRIZE_ALREADY_GOT = 1201;</code>
     */
    const EC_CONTINUE_LOGIN_PRIZE_ALREADY_GOT = 1201;
    /**
     * <pre>
     ******* 世界BOSS错误 *******
     * </pre>
     *
     * <code>EC_WORLDBOSS_ERROR_TIME = 1250;</code>
     */
    const EC_WORLDBOSS_ERROR_TIME = 1250;
    /**
     * <pre>
     * 世界BOSS未开启
     * </pre>
     *
     * <code>EC_WORLDBOSS_ERROR_NOT_OPEN = 1251;</code>
     */
    const EC_WORLDBOSS_ERROR_NOT_OPEN = 1251;
    /**
     * <pre>
     ******* 任务相关错误码 ************
     * </pre>
     *
     * <code>EC_QUEST_ALEADY_ACCEPTED = 1300;</code>
     */
    const EC_QUEST_ALEADY_ACCEPTED = 1300;
    /**
     * <pre>
     * 前置任务没有完成
     * </pre>
     *
     * <code>EC_QUEST_PREV_NOT_FINISHED = 1301;</code>
     */
    const EC_QUEST_PREV_NOT_FINISHED = 1301;
    /**
     * <pre>
     * 任务不可接受
     * </pre>
     *
     * <code>EC_QUEST_NOT_ACCEPTABLE = 1302;</code>
     */
    const EC_QUEST_NOT_ACCEPTABLE = 1302;
    /**
     * <pre>
     * 任务不可完成
     * </pre>
     *
     * <code>EC_QUEST_NOT_FINISHABLE = 1303;</code>
     */
    const EC_QUEST_NOT_FINISHABLE = 1303;
    /**
     * <pre>
     * 任务不可取消
     * </pre>
     *
     * <code>EC_QUEST_NOT_CANCELABLE = 1304;</code>
     */
    const EC_QUEST_NOT_CANCELABLE = 1304;
    /**
     * <pre>
     * 该任务礼包不存在
     * </pre>
     *
     * <code>EC_QUEST_PRIZE_NOT_EXIST = 1305;</code>
     */
    const EC_QUEST_PRIZE_NOT_EXIST = 1305;
    /**
     * <pre>
     * 职业限制不能接取任务
     * </pre>
     *
     * <code>EC_QUEST_ACCEPT_PROFESSION_LIMIT = 1306;</code>
     */
    const EC_QUEST_ACCEPT_PROFESSION_LIMIT = 1306;
    /**
     * <pre>
     ****** 战斗场景错误码 ************
     * </pre>
     *
     * <code>EC_COMBAT_SCENE_NON_VIP = 1400;</code>
     */
    const EC_COMBAT_SCENE_NON_VIP = 1400;
    /**
     * <pre>
     * 战斗数据格式错误
     * </pre>
     *
     * <code>EC_COMBAT_SCENE_ACTION_DATA_WRONG = 1401;</code>
     */
    const EC_COMBAT_SCENE_ACTION_DATA_WRONG = 1401;
    /**
     * <pre>
     * 已经抽取过普通抽奖
     * </pre>
     *
     * <code>EC_COMBAT_SCENE_LOTTERY_DRAWED_BY_NON_VIP = 1402;</code>
     */
    const EC_COMBAT_SCENE_LOTTERY_DRAWED_BY_NON_VIP = 1402;
    /**
     * <pre>
     * VIP抽奖超限
     * </pre>
     *
     * <code>EC_COMBAT_SCENE_LOTTERY_DRAWED_BY_VIP = 1403;</code>
     */
    const EC_COMBAT_SCENE_LOTTERY_DRAWED_BY_VIP = 1403;
    /**
     * <pre>
     * 副本还没有开启, 无法进入
     * </pre>
     *
     * <code>EC_DUNGEON_NOT_OPENED = 1404;</code>
     */
    const EC_DUNGEON_NOT_OPENED = 1404;
    /**
     * <pre>
     * 副本战斗失败
     * </pre>
     *
     * <code>EC_DUNGEON_NOT_SUCCESS_FINISHED = 1405;</code>
     */
    const EC_DUNGEON_NOT_SUCCESS_FINISHED = 1405;
    /**
     * <pre>
     * 副本怪物掉落验证，tid不匹配
     * </pre>
     *
     * <code>EC_COMBAT_DROP_ITEM_TID_WRONG = 1406;</code>
     */
    const EC_COMBAT_DROP_ITEM_TID_WRONG = 1406;
    /**
     * <pre>
     * 副本怪物掉落验证，num不匹配
     * </pre>
     *
     * <code>EC_COMBAT_DROP_ITEM_NUM_WRONG = 1407;</code>
     */
    const EC_COMBAT_DROP_ITEM_NUM_WRONG = 1407;
    /**
     * <pre>
     * 副本怪物掉落验证，index非法
     * </pre>
     *
     * <code>EC_COMBAT_DROP_ITEM_INDEX_WRONG = 1408;</code>
     */
    const EC_COMBAT_DROP_ITEM_INDEX_WRONG = 1408;
    /**
     * <pre>
     * 副本物品拾取验证，index非法
     * </pre>
     *
     * <code>EC_COMBAT_PICK_UP_ITEM_INDEX_WRONG = 1409;</code>
     */
    const EC_COMBAT_PICK_UP_ITEM_INDEX_WRONG = 1409;
    /**
     * <pre>
     * 副本物品拾取验证，status非法
     * </pre>
     *
     * <code>EC_COMBAT_PICK_UP_ITEM_STATUS_WRONG = 1410;</code>
     */
    const EC_COMBAT_PICK_UP_ITEM_STATUS_WRONG = 1410;
    /**
     * <pre>
     * 副本怪物死亡验证，index非法
     * </pre>
     *
     * <code>EC_COMBAT_MONSTER_DIE_INDEX_WRONG = 1411;</code>
     */
    const EC_COMBAT_MONSTER_DIE_INDEX_WRONG = 1411;
    /**
     * <pre>
     * 副本怪物死亡验证，staus非法
     * </pre>
     *
     * <code>EC_COMBAT_MONSTER_DIE_STATUS_WRONG = 1412;</code>
     */
    const EC_COMBAT_MONSTER_DIE_STATUS_WRONG = 1412;
    /**
     * <pre>
     * 副本结束，参数数据非法
     * </pre>
     *
     * <code>EC_COMBAT_FINISH_PARA_DATA_WRONG = 1413;</code>
     */
    const EC_COMBAT_FINISH_PARA_DATA_WRONG = 1413;
    /**
     * <pre>
     * 副本结束，副本status非法
     * </pre>
     *
     * <code>EC_COMBAT_FINISH_DUNGEON_STATUS_WRONG = 1414;</code>
     */
    const EC_COMBAT_FINISH_DUNGEON_STATUS_WRONG = 1414;
    /**
     * <pre>
     * 副本结束，boss status非法
     * </pre>
     *
     * <code>EC_COMBAT_FINISH_BOSS_STATUS_WRONG = 1415;</code>
     */
    const EC_COMBAT_FINISH_BOSS_STATUS_WRONG = 1415;
    /**
     * <pre>
     * 副本结束，monster status非法
     * </pre>
     *
     * <code>EC_COMABT_FINISH_MONSTER_STATUS_WRONG = 1416;</code>
     */
    const EC_COMABT_FINISH_MONSTER_STATUS_WRONG = 1416;
    /**
     * <pre>
     * boss斩杀验证 index非法
     * </pre>
     *
     * <code>EC_COMBAT_BOSS_BEHEADED_BOSS_INDEX_WRONG = 1417;</code>
     */
    const EC_COMBAT_BOSS_BEHEADED_BOSS_INDEX_WRONG = 1417;
    /**
     * <pre>
     * boss斩杀验证 斩杀number超限
     * </pre>
     *
     * <code>EC_COMBAT_BOSS_BEHEADED_NUMBER_OUT_LIMIT = 1418;</code>
     */
    const EC_COMBAT_BOSS_BEHEADED_NUMBER_OUT_LIMIT = 1418;
    /**
     * <pre>
     * 玩家已在战斗中
     * </pre>
     *
     * <code>EC_COMBAT_PLAYER_DUNGEON_INSTANCE_NOT_NULL = 1419;</code>
     */
    const EC_COMBAT_PLAYER_DUNGEON_INSTANCE_NOT_NULL = 1419;
    /**
     * <pre>
     * 玩家已经在队伍中
     * </pre>
     *
     * <code>EC_COMBAT_PLAYER_IS_ALREADY_IN_TEAM = 1420;</code>
     */
    const EC_COMBAT_PLAYER_IS_ALREADY_IN_TEAM = 1420;
    /**
     * <pre>
     * 玩家死亡状态错误
     * </pre>
     *
     * <code>EC_COMBAT_PLAYER_DIE_STATUS_ERROR = 1421;</code>
     */
    const EC_COMBAT_PLAYER_DIE_STATUS_ERROR = 1421;
    /**
     * <pre>
     * 玩家已经死亡
     * </pre>
     *
     * <code>EC_COMBAT_PLAYER_DIED = 1422;</code>
     */
    const EC_COMBAT_PLAYER_DIED = 1422;
    /**
     * <pre>
     * 该副本不可扫荡
     * </pre>
     *
     * <code>EC_COMBAT_DUNGEON_CAN_NOT_SWEEP = 1423;</code>
     */
    const EC_COMBAT_DUNGEON_CAN_NOT_SWEEP = 1423;
    /**
     * <pre>
     ****** 竞技场挑战错误码 **********
     * </pre>
     *
     * <code>EC_ARENA_CHALLENGE_TIME_OUT = 1501;</code>
     */
    const EC_ARENA_CHALLENGE_TIME_OUT = 1501;
    /**
     * <pre>
     * 竞技场排名奖励已经领取完毕
     * </pre>
     *
     * <code>EC_ARENA_RANKING_PRIZE_GOT = 1502;</code>
     */
    const EC_ARENA_RANKING_PRIZE_GOT = 1502;
    /**
     * <pre>
     * 竞技场模块未开启
     * </pre>
     *
     * <code>EC_ARENA_NOT_OPEN = 1503;</code>
     */
    const EC_ARENA_NOT_OPEN = 1503;
    /**
     * <pre>
     * 竞技场排名更新
     * </pre>
     *
     * <code>EC_ARENA_RANKING_UPDATE = 1504;</code>
     */
    const EC_ARENA_RANKING_UPDATE = 1504;
    /**
     * <pre>
     * 挑战的排名非匹配的排名
     * </pre>
     *
     * <code>EC_ARENA_CHALLENGE_RANKING_NOT_IN_MATCH_PLAYERS = 1505;</code>
     */
    const EC_ARENA_CHALLENGE_RANKING_NOT_IN_MATCH_PLAYERS = 1505;
    /**
     * <pre>
     * 无匹配玩家
     * </pre>
     *
     * <code>EC_ARENA_MATCH_PLAYERS_NOT_EXIST = 1506;</code>
     */
    const EC_ARENA_MATCH_PLAYERS_NOT_EXIST = 1506;
    /**
     * <pre>
     * 被挑战玩家排名发生变化
     * </pre>
     *
     * <code>EC_ARENA_CHALLENGE_PLAYER_DATA_CHANGED = 1507;</code>
     */
    const EC_ARENA_CHALLENGE_PLAYER_DATA_CHANGED = 1507;
    /**
     * <pre>
     * 被挑战玩家正在挑战
     * </pre>
     *
     * <code>EC_ARENA_PLAYER_IS_CHALLENGING = 1508;</code>
     */
    const EC_ARENA_PLAYER_IS_CHALLENGING = 1508;
    /**
     * <pre>
     * 自己正在被挑战
     * </pre>
     *
     * <code>EC_ARENA_PLAYER_BEEN_CHALLENEGED = 1509;</code>
     */
    const EC_ARENA_PLAYER_BEEN_CHALLENEGED = 1509;
    /**
     * <pre>
     * 自己的排名已发生变化
     * </pre>
     *
     * <code>EC_ARENA_PLAYER_RANKING_CHANGED = 1510;</code>
     */
    const EC_ARENA_PLAYER_RANKING_CHANGED = 1510;
    /**
     * <pre>
     ****** 血战 错误码 ************
     * </pre>
     *
     * <code>EC_XUEZHAN_BUY_MATERIAL_NOT_ENOUGH = 1600;</code>
     */
    const EC_XUEZHAN_BUY_MATERIAL_NOT_ENOUGH = 1600;
    /**
     * <pre>
     * 已无挑战次数
     * </pre>
     *
     * <code>EC_XUEZHAN_NOT_PERMIT_TIMES = 1601;</code>
     */
    const EC_XUEZHAN_NOT_PERMIT_TIMES = 1601;
    /**
     * <pre>
     * 星级不足
     * </pre>
     *
     * <code>EC_XUEZHAN_STARS_NOT_ENOUGH = 1602;</code>
     */
    const EC_XUEZHAN_STARS_NOT_ENOUGH = 1602;
    /**
     * <pre>
     * 无法领取奖励
     * </pre>
     *
     * <code>EC_XUEZHAN_STARS_CANT_OPEN_REWARD = 1603;</code>
     */
    const EC_XUEZHAN_STARS_CANT_OPEN_REWARD = 1603;
    /**
     * <pre>
     ****** 屠龙夺宝 错误码 ************
     * </pre>
     *
     * <code>EC_TULONG_DRAGON_HP_ERROR = 1650;</code>
     */
    const EC_TULONG_DRAGON_HP_ERROR = 1650;
    /**
     * <pre>
     * 龙飞走了
     * </pre>
     *
     * <code>EC_TULONG_DRAGON_DEAD = 1651;</code>
     */
    const EC_TULONG_DRAGON_DEAD = 1651;
    /**
     * <pre>
     *======================== 公会 ======================//
     * </pre>
     *
     * <code>EC_ALREADY_IN_GUILD = 1700;</code>
     */
    const EC_ALREADY_IN_GUILD = 1700;
    /**
     * <pre>
     * 对方已经在公会中
     * </pre>
     *
     * <code>EC_TARGET_ALREADY_IN_GUILD = 1701;</code>
     */
    const EC_TARGET_ALREADY_IN_GUILD = 1701;
    /**
     * <pre>
     * 没有加入公会
     * </pre>
     *
     * <code>EC_NOT_IN_GUILD = 1702;</code>
     */
    const EC_NOT_IN_GUILD = 1702;
    /**
     * <pre>
     * 公会已满
     * </pre>
     *
     * <code>EC_REACH_MAX_GUILD_MEMBER_NUM = 1703;</code>
     */
    const EC_REACH_MAX_GUILD_MEMBER_NUM = 1703;
    /**
     * <pre>
     * 公会权限不够
     * </pre>
     *
     * <code>EC_GUILD_NO_PRIVILEGE = 1704;</code>
     */
    const EC_GUILD_NO_PRIVILEGE = 1704;
    /**
     * <pre>
     * 没有找到该公会申请
     * </pre>
     *
     * <code>EC_NOT_FOUND_GUILD_APPLY = 1705;</code>
     */
    const EC_NOT_FOUND_GUILD_APPLY = 1705;
    /**
     * <pre>
     * 已经申请工会
     * </pre>
     *
     * <code>EC_ALREADY_APPLY_GUILD = 1706;</code>
     */
    const EC_ALREADY_APPLY_GUILD = 1706;
    /**
     * <pre>
     * 公会还有其他成员, 会长不能离开
     * </pre>
     *
     * <code>EC_NO_PRESIDENT_QUIT_WITH_MEMBER = 1707;</code>
     */
    const EC_NO_PRESIDENT_QUIT_WITH_MEMBER = 1707;
    /**
     * <pre>
     * 公会购买次数超限
     * </pre>
     *
     * <code>EC_GUILD_PURCHASE_COUNT_OUT_OF_LIMIT = 1708;</code>
     */
    const EC_GUILD_PURCHASE_COUNT_OUT_OF_LIMIT = 1708;
    /**
     * <pre>
     * 公会随机商店物品已出售
     * </pre>
     *
     * <code>EC_GUILD_RANDOM_SHOP_PURCHASE_ITEM_FLAG_ERROR = 1709;</code>
     */
    const EC_GUILD_RANDOM_SHOP_PURCHASE_ITEM_FLAG_ERROR = 1709;
    /**
     * <pre>
     * 公会等级不足，固定商店中物品无法购买
     * </pre>
     *
     * <code>EC_GUILD_FIXED_SHOP_GUILD_LEVEL_LIMTED = 1710;</code>
     */
    const EC_GUILD_FIXED_SHOP_GUILD_LEVEL_LIMTED = 1710;
    /**
     * <pre>
     * 公会等级不足，随机商店中物品无法购买
     * </pre>
     *
     * <code>EC_GUILD_RANDOM_SHOP_GUILD_LEVEL_LIMTED = 1711;</code>
     */
    const EC_GUILD_RANDOM_SHOP_GUILD_LEVEL_LIMTED = 1711;
    /**
     * <pre>
     * 创建公会 名字重复
     * </pre>
     *
     * <code>EC_GUILD_CREATE_DUPLICATE_NAME = 1712;</code>
     */
    const EC_GUILD_CREATE_DUPLICATE_NAME = 1712;
    /**
     * <pre>
     * 创建公会 名字非法
     * </pre>
     *
     * <code>EC_GUILD_CREATE_ILLEGAL_NAME = 1713;</code>
     */
    const EC_GUILD_CREATE_ILLEGAL_NAME = 1713;
    /**
     * <pre>
     * 创建公会 名字太短
     * </pre>
     *
     * <code>EC_GUILD_CREATE_NAME_TOO_SHORT = 1714;</code>
     */
    const EC_GUILD_CREATE_NAME_TOO_SHORT = 1714;
    /**
     * <pre>
     * 创建公会 名字太长
     * </pre>
     *
     * <code>EC_GUILD_CREATE_NAME_TOO_LONG = 1715;</code>
     */
    const EC_GUILD_CREATE_NAME_TOO_LONG = 1715;
    /**
     * <pre>
     *********斗神台 错误码************
     * </pre>
     *
     * <code>EC_FIGHT_GOD_SQUARE_NOT_OPEN = 1800;</code>
     */
    const EC_FIGHT_GOD_SQUARE_NOT_OPEN = 1800;
    /**
     * <pre>
     * 积分不足
     * </pre>
     *
     * <code>EC_FIGHT_GOD_SQUARE_SCORE_NOT_ENOUGH = 1801;</code>
     */
    const EC_FIGHT_GOD_SQUARE_SCORE_NOT_ENOUGH = 1801;
    /**
     * <pre>
     * 挑战超时
     * </pre>
     *
     * <code>EC_FIGHT_GOD_SQUARE_CHALLENGE_OUT_TIME = 1802;</code>
     */
    const EC_FIGHT_GOD_SQUARE_CHALLENGE_OUT_TIME = 1802;
    /**
     * <pre>
     * 无匹配玩家
     * </pre>
     *
     * <code>EC_FIGHT_GOD_SQUARE_NOT_EXIST_MATCH_PLAYER = 1803;</code>
     */
    const EC_FIGHT_GOD_SQUARE_NOT_EXIST_MATCH_PLAYER = 1803;
    /**
     * <pre>
     ********* 好友系统 错误码 **********
     * </pre>
     *
     * <code>EC_FRIENDS_PLAYER_NOT_EXIST = 1901;</code>
     */
    const EC_FRIENDS_PLAYER_NOT_EXIST = 1901;
    /**
     * <pre>
     * 已向该好友发出过申请
     * </pre>
     *
     * <code>EC_FRIENDS_APPLYED_EXIST = 1902;</code>
     */
    const EC_FRIENDS_APPLYED_EXIST = 1902;
    /**
     * <pre>
     * 已是好友
     * </pre>
     *
     * <code>EC_FRIENDS_FRIENDS_EXIST = 1903;</code>
     */
    const EC_FRIENDS_FRIENDS_EXIST = 1903;
    /**
     * <pre>
     * 对方好友已满
     * </pre>
     *
     * <code>EC_FRIENDS_APPLYED_FRIENDS_OUT_LIMIT = 1904;</code>
     */
    const EC_FRIENDS_APPLYED_FRIENDS_OUT_LIMIT = 1904;
    /**
     * <pre>
     * 自己好友已满
     * </pre>
     *
     * <code>EC_FRIENDS_OWN_FRIENDS_OUT_LIMIT = 1905;</code>
     */
    const EC_FRIENDS_OWN_FRIENDS_OUT_LIMIT = 1905;
    /**
     * <pre>
     * 不存在该好友
     * </pre>
     *
     * <code>EC_FRIENDS_NOT_EXIST = 1906;</code>
     */
    const EC_FRIENDS_NOT_EXIST = 1906;
    /**
     * <pre>
     * 好友索取宝箱次数超限
     * </pre>
     *
     * <code>EC_FRIENDS_TREASURE_REQUEST_OUT_LIMTI = 1907;</code>
     */
    const EC_FRIENDS_TREASURE_REQUEST_OUT_LIMTI = 1907;
    /**
     * <pre>
     * 已向该好友索取过宝箱
     * </pre>
     *
     * <code>EC_FRIENDS_TREASURE_REQURESTED = 1908;</code>
     */
    const EC_FRIENDS_TREASURE_REQURESTED = 1908;
    /**
     * <pre>
     * 已赠送
     * </pre>
     *
     * <code>EC_FRIENDS_ALREADY_DONATED = 1909;</code>
     */
    const EC_FRIENDS_ALREADY_DONATED = 1909;
    /**
     * <pre>
     * 赠送好友福利超限
     * </pre>
     *
     * <code>EC_FRIENDS_DONATE_OUT_LIMIT = 1910;</code>
     */
    const EC_FRIENDS_DONATE_OUT_LIMIT = 1910;
    /**
     * <pre>
     * 好友申请对象不能是自己
     * </pre>
     *
     * <code>EC_FRIENDS_IS_SELF = 1911;</code>
     */
    const EC_FRIENDS_IS_SELF = 1911;
    /**
     * <pre>
     ********* 组队系统 错误码 ***********
     * </pre>
     *
     * <code>EC_TEAMS_PLAYER_ALREADY_IN_TEAM = 2000;</code>
     */
    const EC_TEAMS_PLAYER_ALREADY_IN_TEAM = 2000;
    /**
     * <pre>
     * 玩家已在其他队伍中
     * </pre>
     *
     * <code>EC_TEAMS_PLYAER_ALREADY_IN_OTHER_TEAM = 2001;</code>
     */
    const EC_TEAMS_PLYAER_ALREADY_IN_OTHER_TEAM = 2001;
    /**
     * <pre>
     * 成员不存在
     * </pre>
     *
     * <code>EC_TEAMS_MEMBER_NOT_IN_TEAM = 2002;</code>
     */
    const EC_TEAMS_MEMBER_NOT_IN_TEAM = 2002;
    /**
     * <pre>
     * 未选择关卡
     * </pre>
     *
     * <code>EC_TEAMS_NOT_SET_DUNGEON_ID = 2003;</code>
     */
    const EC_TEAMS_NOT_SET_DUNGEON_ID = 2003;
    /**
     * <pre>
     * 队伍不存在
     * </pre>
     *
     * <code>EC_TEAMS_NOT_EXIST_TEAM = 2004;</code>
     */
    const EC_TEAMS_NOT_EXIST_TEAM = 2004;
    /**
     * <pre>
     * 队员不在该场景
     * </pre>
     *
     * <code>EC_TEAMS_MEMBER_NOT_IN_SCENE = 2005;</code>
     */
    const EC_TEAMS_MEMBER_NOT_IN_SCENE = 2005;
    /**
     * <pre>
     * 该场景不存在该副本
     * </pre>
     *
     * <code>EC_TEAMS_SCENE_NOT_EXIST_DUNGEON_ID = 2006;</code>
     */
    const EC_TEAMS_SCENE_NOT_EXIST_DUNGEON_ID = 2006;
    /**
     * <pre>
     * 玩家在其他队伍中，不可创建队伍
     * </pre>
     *
     * <code>EC_TEAMS_PLAYER_ALREADY_IN_OTHER_TEAM = 2007;</code>
     */
    const EC_TEAMS_PLAYER_ALREADY_IN_OTHER_TEAM = 2007;
    /**
     * <pre>
     * 其他场景的队伍，不可加入
     * </pre>
     *
     * <code>EC_TEAMS_PLAYER_NOT_IN_TEAM_SCENE = 2008;</code>
     */
    const EC_TEAMS_PLAYER_NOT_IN_TEAM_SCENE = 2008;
    /**
     * <pre>
     * 队伍已经满员
     * </pre>
     *
     * <code>EC_TEAMS_MEMBERS_NUM_OUT_RANGE = 2009;</code>
     */
    const EC_TEAMS_MEMBERS_NUM_OUT_RANGE = 2009;
    /**
     * <pre>
     ****** 可领取背包 *******
     * </pre>
     *
     * <code>EC_RECEIVABLE_PACK_ALREADY_PICKED = 2100;</code>
     */
    const EC_RECEIVABLE_PACK_ALREADY_PICKED = 2100;
    /**
     * <pre>
     *******邮件 *********
     * </pre>
     *
     * <code>EC_MAIL_ALREADY_PICKED = 2200;</code>
     */
    const EC_MAIL_ALREADY_PICKED = 2200;
    /**
     * <pre>
     * 邮件已读取
     * </pre>
     *
     * <code>EC_MAIL_ALREADY_READ = 2201;</code>
     */
    const EC_MAIL_ALREADY_READ = 2201;
    /**
     * <pre>
     * 积分不足，不可购买
     * </pre>
     *
     * <code>EC_HONOUR_SHOP_SCORE_NOT_ENOUGH = 2210;</code>
     */
    const EC_HONOUR_SHOP_SCORE_NOT_ENOUGH = 2210;
    /**
     * <pre>
     *******人物进阶*********
     * </pre>
     *
     * <code>EC_PROSESSION_TRANS_LESS_EQUIP = 2250;</code>
     */
    const EC_PROSESSION_TRANS_LESS_EQUIP = 2250;
    /**
     * <pre>
     *******密境*******
     * </pre>
     *
     * <code>EC_MIJING_COUNT_ERROR = 2300;</code>
     */
    const EC_MIJING_COUNT_ERROR = 2300;
    /**
     * <pre>
     * 重复进入
     * </pre>
     *
     * <code>EC_MIJING_DOING = 2301;</code>
     */
    const EC_MIJING_DOING = 2301;
    /**
     * <pre>
     * 当天月卡福利已经领取
     * </pre>
     *
     * <code>EC_MONTH_CARD_WELFARE_PICKED = 2351;</code>
     */
    const EC_MONTH_CARD_WELFARE_PICKED = 2351;
    /**
     * <pre>
     * 未到体力领取时间
     * </pre>
     *
     * <code>EC_SPIRIT_COLLECT_TIME_ERROR = 2360;</code>
     */
    const EC_SPIRIT_COLLECT_TIME_ERROR = 2360;
    /**
     * <pre>
     * 该时间段体力已领取
     * </pre>
     *
     * <code>EC_SPIRIT_COLLECTED_BY_TIME_PRIOD = 2361;</code>
     */
    const EC_SPIRIT_COLLECTED_BY_TIME_PRIOD = 2361;
    /**
     * <pre>
     * 战斗结束状态错误
     * </pre>
     *
     * <code>EC_COMBAT_FINISH_DUNGEON_ERROR = 2362;</code>
     */
    const EC_COMBAT_FINISH_DUNGEON_ERROR = 2362;
    /**
     * <pre>
     * 扫荡所需vip等级不足  
     * </pre>
     *
     * <code>EC_COMBAT_SWEEP_DUNGEON_VIP_LEVEL_LIMIT = 2364;</code>
     */
    const EC_COMBAT_SWEEP_DUNGEON_VIP_LEVEL_LIMIT = 2364;
    /**
     * <pre>
     *********签到********
     * </pre>
     *
     * <code>EC_CHECK_DAY_ORDER_CHECKED = 2400;</code>
     */
    const EC_CHECK_DAY_ORDER_CHECKED = 2400;
    /**
     * <pre>
     * 客户端签到时间错误
     * </pre>
     *
     * <code>EC_CHECK_CIENT_TIME_INVALID = 2401;</code>
     */
    const EC_CHECK_CIENT_TIME_INVALID = 2401;
    /**
     * <pre>
     * 角色创建index非法
     * </pre>
     *
     * <code>EC_PLAYER_CREATE_INDEX_INVALID = 2410;</code>
     */
    const EC_PLAYER_CREATE_INDEX_INVALID = 2410;
    /**
     * <pre>
     *查询玩家数据失败
     * </pre>
     *
     * <code>EC_QUERY_PLAYER_DATA_FAILED = 2500;</code>
     */
    const EC_QUERY_PLAYER_DATA_FAILED = 2500;
    /**
     * <pre>
     * 战斗数据异常，验证未通过，战斗无效
     * </pre>
     *
     * <code>EC_COMBAT_VERIFICATION_FAILED = 2501;</code>
     */
    const EC_COMBAT_VERIFICATION_FAILED = 2501;
    /**
     * <pre>
     **** 删除角色 ****
     * </pre>
     *
     * <code>EC_DELETE_PYLATER_INVALID_ACOUNTID = 2601;</code>
     */
    const EC_DELETE_PYLATER_INVALID_ACOUNTID = 2601;
    /**
     * <pre>
     * 角色id无效
     * </pre>
     *
     * <code>EC_DELETE_PYLATER_INVALID_PYLATERID = 2602;</code>
     */
    const EC_DELETE_PYLATER_INVALID_PYLATERID = 2602;
    /**
     * <pre>
     * 超过龙巢最大编号
     * </pre>
     *
     * <code>EC_NEST_INDEX_ERROR = 2603;</code>
     */
    const EC_NEST_INDEX_ERROR = 2603;
    /**
     * <pre>
     * 你没有这个神龙
     * </pre>
     *
     * <code>EC_NEST_RELICS_UID_ERROR = 2604;</code>
     */
    const EC_NEST_RELICS_UID_ERROR = 2604;
    /**
     * <pre>
     * 这个道具不是神龙
     * </pre>
     *
     * <code>EC_NEST_RELICS_TYPE_ERROR = 2605;</code>
     */
    const EC_NEST_RELICS_TYPE_ERROR = 2605;
    /**
     * <pre>
     * 添加神龙奖励失败
     * </pre>
     *
     * <code>EC_NEST_RELICS_REWARD_ERROR = 2606;</code>
     */
    const EC_NEST_RELICS_REWARD_ERROR = 2606;
    /**
     * <pre>
     * 找不到神龙奖励配置
     * </pre>
     *
     * <code>EC_NEST_RELICS_CONFIG_ERROR = 2607;</code>
     */
    const EC_NEST_RELICS_CONFIG_ERROR = 2607;
    /**
     * <pre>
     * 超过龙巢最大等级
     * </pre>
     *
     * <code>EC_NEST_RELICS_LEVEL_ERROR = 2608;</code>
     */
    const EC_NEST_RELICS_LEVEL_ERROR = 2608;
    /**
     * <pre>
     * 没有足够的元宝升级龙巢
     * </pre>
     *
     * <code>EC_NEST_RELICS_LEVELUP_ERROR = 2609;</code>
     */
    const EC_NEST_RELICS_LEVELUP_ERROR = 2609;
    /**
     * <pre>
     * 找不到对手
     * </pre>
     *
     * <code>EC_NEST_RELICS_OPP_ERROR = 2610;</code>
     */
    const EC_NEST_RELICS_OPP_ERROR = 2610;
    /**
     * <pre>
     * 没有掠夺次数
     * </pre>
     *
     * <code>EC_NEST_RELICS_SNATCH_COUNT_ERROR = 2611;</code>
     */
    const EC_NEST_RELICS_SNATCH_COUNT_ERROR = 2611;
    /**
     * <pre>
     * 龙巢被锁定
     * </pre>
     *
     * <code>EC_NEST_RELICS_LOCK_ERROR = 2612;</code>
     */
    const EC_NEST_RELICS_LOCK_ERROR = 2612;
    /**
     * <pre>
     * 龙巢已经被占用
     * </pre>
     *
     * <code>EC_NEST_RELICS_TRAIN_HAVE_PLAYER_ERROR = 2613;</code>
     */
    const EC_NEST_RELICS_TRAIN_HAVE_PLAYER_ERROR = 2613;
    /**
     * <pre>
     * 神龙已经在训练
     * </pre>
     *
     * <code>EC_NEST_RELICS_TRAIN_AGAIN_ERROR = 2614;</code>
     */
    const EC_NEST_RELICS_TRAIN_AGAIN_ERROR = 2614;
    /**
     * <pre>
     * 搜索需要的金币不够
     * </pre>
     *
     * <code>EC_NEST_RELICS_SEARCH_PAY_ERROR = 2615;</code>
     */
    const EC_NEST_RELICS_SEARCH_PAY_ERROR = 2615;
    /**
     * <pre>
     * 对方神龙保护状态中
     * </pre>
     *
     * <code>EC_NEST_RELICS_PROTECTED = 2616;</code>
     */
    const EC_NEST_RELICS_PROTECTED = 2616;
    /**
     * <pre>
     * 符石类型错误
     * </pre>
     *
     * <code>EC_FUSHI_TYPE_ERROR = 2617;</code>
     */
    const EC_FUSHI_TYPE_ERROR = 2617;
    /**
     * <pre>
     * 没有镶嵌的符石
     * </pre>
     *
     * <code>EC_FUSHI_UNEQUIP_ERROR = 2618;</code>
     */
    const EC_FUSHI_UNEQUIP_ERROR = 2618;
    /**
     * <pre>
     * 重复镶嵌符石
     * </pre>
     *
     * <code>EC_FUSHI_EQUIP_RE_ERROR = 2619;</code>
     */
    const EC_FUSHI_EQUIP_RE_ERROR = 2619;
    /**
     * <pre>
     * 未找到符石
     * </pre>
     *
     * <code>EC_FUSHI_EQUIP_NOTFOUND_ERROR = 2620;</code>
     */
    const EC_FUSHI_EQUIP_NOTFOUND_ERROR = 2620;
    /**
     * <pre>
     * 未找到符石配置
     * </pre>
     *
     * <code>EC_FUSHI_NOTFOUND_ERROR = 2621;</code>
     */
    const EC_FUSHI_NOTFOUND_ERROR = 2621;
    /**
     * <pre>
     * 符石不能超过人物等级
     * </pre>
     *
     * <code>EC_FUSHI_EAT_ERROR = 2622;</code>
     */
    const EC_FUSHI_EAT_ERROR = 2622;
    /**
     * <pre>
     *请强化神龙
     * </pre>
     *
     * <code>EC_RELICS_NEED_STRENGTH_ERROR = 2623;</code>
     */
    const EC_RELICS_NEED_STRENGTH_ERROR = 2623;
    /**
     * <pre>
     *请突破神龙
     * </pre>
     *
     * <code>EC_RELICS_NEED_CLASS_ERROR = 2624;</code>
     */
    const EC_RELICS_NEED_CLASS_ERROR = 2624;
    /**
     * <pre>
     *位置被锁定
     * </pre>
     *
     * <code>EC_FUSHI_EQUIP_LOCK_ERROR = 2625;</code>
     */
    const EC_FUSHI_EQUIP_LOCK_ERROR = 2625;
    /**
     * <pre>
     * 随机商店物品已售罄
     * </pre>
     *
     * <code>EC_RANDOM_SHOP_ITEM_SALE_OUT = 2640;</code>
     */
    const EC_RANDOM_SHOP_ITEM_SALE_OUT = 2640;
    /**
     * <pre>
     * 未到达礼包领取时间
     * </pre>
     *
     * <code>EC_ONLINE_PRIZE_PICK_TIME_NOT_REACH = 2700;</code>
     */
    const EC_ONLINE_PRIZE_PICK_TIME_NOT_REACH = 2700;
    /**
     * <pre>
     * 已无可领取的在线礼包
     * </pre>
     *
     * <code>EC_ONLINE_PRIZE_PICK_NOT_EXIST_RECEIVABLE_PACK = 2701;</code>
     */
    const EC_ONLINE_PRIZE_PICK_NOT_EXIST_RECEIVABLE_PACK = 2701;
    /**
     * <pre>
     * 礼包无效
     * </pre>
     *
     * <code>EC_INVALID_RECEIVABLE_PACK = 2702;</code>
     */
    const EC_INVALID_RECEIVABLE_PACK = 2702;
    /**
     * <pre>
     * 服务器未开放
     * </pre>
     *
     * <code>EC_SERVER_UNOPEN = 2703;</code>
     */
    const EC_SERVER_UNOPEN = 2703;
    /**
     * <pre>
     * 天梯未开放
     * </pre>
     *
     * <code>EC_LADDER_UNOPEN = 2704;</code>
     */
    const EC_LADDER_UNOPEN = 2704;
    /**
     * <pre>
     * 礼包码请求无效
     * </pre>
     *
     * <code>EC_CDK_ERROR_HTTP_REQUEST = 2705;</code>
     */
    const EC_CDK_ERROR_HTTP_REQUEST = 2705;
    /**
     * <pre>
     * 礼包码状态错误
     * </pre>
     *
     * <code>EC_CDK_CODE_ERROR = 2706;</code>
     */
    const EC_CDK_CODE_ERROR = 2706;
    /**
     * <pre>
     * VIP等级没到
     * </pre>
     *
     * <code>EC_MALL_VIP_ERROR = 2707;</code>
     */
    const EC_MALL_VIP_ERROR = 2707;
    /**
     * <pre>
     * 次数超过
     * </pre>
     *
     * <code>EC_MALL_COUNT_ERROR = 2708;</code>
     */
    const EC_MALL_COUNT_ERROR = 2708;
    /**
     * <pre>
     * 服务器次数超过
     * </pre>
     *
     * <code>EC_MALL_GLOBAL_COUNT_ERROR = 2709;</code>
     */
    const EC_MALL_GLOBAL_COUNT_ERROR = 2709;
    /**
     * <pre>
     * 未找到道具
     * </pre>
     *
     * <code>EC_MALL_NOT_FOUND = 2710;</code>
     */
    const EC_MALL_NOT_FOUND = 2710;
    /**
     * <pre>
     * 未在买道具时间内
     * </pre>
     *
     * <code>EC_MALL_ITEM_NOT_IN_TIME = 2711;</code>
     */
    const EC_MALL_ITEM_NOT_IN_TIME = 2711;
    /**
     * <pre>
     * 题目不匹配
     * </pre>
     *
     * <code>EC_QUESTION_ERROR = 2720;</code>
     */
    const EC_QUESTION_ERROR = 2720;
    /**
     * <pre>
     * 答题已经结束
     * </pre>
     *
     * <code>EC_QUESTION_TIME_ERROR = 2721;</code>
     */
    const EC_QUESTION_TIME_ERROR = 2721;
    /**
     * <pre>
     * 超过最大长度
     * </pre>
     *
     * <code>EC_QUESTION_LENGTH_ERROR = 2722;</code>
     */
    const EC_QUESTION_LENGTH_ERROR = 2722;
    /**
     * <pre>
     * 答题还没开始
     * </pre>
     *
     * <code>EC_QUESTION_NOT_BEGIN_ERROR = 2723;</code>
     */
    const EC_QUESTION_NOT_BEGIN_ERROR = 2723;
    /**
     * <pre>
     * 签到VIP 补领，状态不可领取
     * </pre>
     *
     * <code>EC_VIP_RESTROACTIVE_AWARD_UNRECEIVABLE = 2724;</code>
     */
    const EC_VIP_RESTROACTIVE_AWARD_UNRECEIVABLE = 2724;
    /**
     * <pre>
     * 签到VIP 补领，vip等级未达到   
     * </pre>
     *
     * <code>EC_VIP_RESTROACTIVE_AWARD_VIP_UNREACH = 2725;</code>
     */
    const EC_VIP_RESTROACTIVE_AWARD_VIP_UNREACH = 2725;
    /**
     * <pre>
     * 签到VIP 补领，VIP 数据错误
     * </pre>
     *
     * <code>EC_VIP_RESTROACTIVE_AWARD_VIP_DATAT_ERROR = 2726;</code>
     */
    const EC_VIP_RESTROACTIVE_AWARD_VIP_DATAT_ERROR = 2726;
    /**
     * <pre>
     * 签到VIP 补领，倍率配置错误
     * </pre>
     *
     * <code>EC_VIP_RESTROACTIVE_AWARD_RATE_ERROR = 2727;</code>
     */
    const EC_VIP_RESTROACTIVE_AWARD_RATE_ERROR = 2727;
    /**
     * <pre>
     * 章节宝箱未开启
     * </pre>
     *
     * <code>EC_CHAPTER_BOX_UNOPEN = 2728;</code>
     */
    const EC_CHAPTER_BOX_UNOPEN = 2728;
    /**
     * <pre>
     * 章节宝箱已领取
     * </pre>
     *
     * <code>EC_CHAPTER_BOX_RECEIVED = 2729;</code>
     */
    const EC_CHAPTER_BOX_RECEIVED = 2729;
    /**
     * <pre>
     * 活动不可接受
     * </pre>
     *
     * <code>EC_ACTIVITY_NOT_ACCEPTABLE = 3101;</code>
     */
    const EC_ACTIVITY_NOT_ACCEPTABLE = 3101;
    /**
     * <pre>
     * 活动奖励不可接受
     * </pre>
     *
     * <code>EC_ACTIVITY_AWARD_NOT_ACCEPTABLE = 3102;</code>
     */
    const EC_ACTIVITY_AWARD_NOT_ACCEPTABLE = 3102;
    /**
     * <pre>
     * 奖励未完成
     * </pre>
     *
     * <code>EC_AWARD_UNFINISHED = 3103;</code>
     */
    const EC_AWARD_UNFINISHED = 3103;
    /**
     * <pre>
     * 错误活动时间
     * </pre>
     *
     * <code>EC_ERROR_AWARD_TIME = 3104;</code>
     */
    const EC_ERROR_AWARD_TIME = 3104;
    /**
     * <pre>
     * 领奖次数达到上限
     * </pre>
     *
     * <code>EC_EXCEEDED_RECV_COUNT = 3105;</code>
     */
    const EC_EXCEEDED_RECV_COUNT = 3105;
    /**
     * <pre>
     * 奖励已领取
     * </pre>
     *
     * <code>EC_AWARD_RECEIVED = 3106;</code>
     */
    const EC_AWARD_RECEIVED = 3106;
    /**
     * <pre>
     *服务器返回数据格式错误
     * </pre>
     *
     * <code>EC_GVR_HTTP_REQUEST_JSON_ERROR = 3500;</code>
     */
    const EC_GVR_HTTP_REQUEST_JSON_ERROR = 3500;
    /**
     * <pre>
     * 礼包码状态错误
     * </pre>
     *
     * <code>EC_GVR_CODE_ERROR = 3501;</code>
     */
    const EC_GVR_CODE_ERROR = 3501;
    /**
     * <pre>
     ******************* 组队 *************************
     * </pre>
     *
     * <code>EC_TEAM_NOT_OPEN_TIME = 3201;</code>
     */
    const EC_TEAM_NOT_OPEN_TIME = 3201;
    /**
     * <pre>
     * 玩家断线
     * </pre>
     *
     * <code>EC_TEAM_PLAYER_OFFLINE = 3202;</code>
     */
    const EC_TEAM_PLAYER_OFFLINE = 3202;
    /**
     * <pre>
     * 邀请者离开
     * </pre>
     *
     * <code>EC_TEAM_INVITER_LEAVE = 3203;</code>
     */
    const EC_TEAM_INVITER_LEAVE = 3203;
    /**
     * <pre>
     * 匹配玩家失败
     * </pre>
     *
     * <code>EC_TEAM_MATCH_FAILD = 3204;</code>
     */
    const EC_TEAM_MATCH_FAILD = 3204;
    /**
     * <pre>
     ******************* 多人PVP *************************
     * </pre>
     *
     * <code>EC_MULTI_PVP_LEVEL_LIMIT = 3301;</code>
     */
    const EC_MULTI_PVP_LEVEL_LIMIT = 3301;
    /**
     * <pre>
     * 队友限制次数用光
     * </pre>
     *
     * <code>EC_MULTI_PVP_TEAMMATE_COUNT_REACH_MAX = 3302;</code>
     */
    const EC_MULTI_PVP_TEAMMATE_COUNT_REACH_MAX = 3302;
}

