<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 基本属性
 * </pre>
 *
 * Protobuf type <code>proto.playerinfo.BasePlayAttribute</code>
 */
class BasePlayAttribute extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 role_id = 1;</code>
     */
    private $role_id = 0;
    /**
     * <code>int32 gender = 2;</code>
     */
    private $gender = 0;
    /**
     * <code>int32 level = 3;</code>
     */
    private $level = 0;
    /**
     * <pre>
     *力量
     * </pre>
     *
     * <code>int32 strength = 4;</code>
     */
    private $strength = 0;
    /**
     * <pre>
     *敏捷
     * </pre>
     *
     * <code>int32 agile = 5;</code>
     */
    private $agile = 0;
    /**
     * <pre>
     * 智力
     * </pre>
     *
     * <code>int32 intelligence = 6;</code>
     */
    private $intelligence = 0;
    /**
     * <pre>
     *体质
     * </pre>
     *
     * <code>int32 vit = 7;</code>
     */
    private $vit = 0;
    /**
     * <pre>
     *最大生命值
     * </pre>
     *
     * <code>int32 max_hp = 8;</code>
     */
    private $max_hp = 0;
    /**
     * <pre>
     *攻击力
     * </pre>
     *
     * <code>int32 atack = 9;</code>
     */
    private $atack = 0;
    /**
     * <pre>
     *防御力
     * </pre>
     *
     * <code>int32 def = 10;</code>
     */
    private $def = 0;
    /**
     * <pre>
     * 神圣属性防御
     * </pre>
     *
     * <code>int32 mag_def1 = 11;</code>
     */
    private $mag_def1 = 0;
    /**
     * <pre>
     *暗影属性防御
     * </pre>
     *
     * <code>int32 mag_def2 = 12;</code>
     */
    private $mag_def2 = 0;
    /**
     * <pre>
     *暴击几率
     * </pre>
     *
     * <code>int32 crit_chance = 13;</code>
     */
    private $crit_chance = 0;
    /**
     * <pre>
     * 必杀伤害加成几率
     * </pre>
     *
     * <code>int32 slay_p = 14;</code>
     */
    private $slay_p = 0;
    /**
     * <pre>
     *闪避几率
     * </pre>
     *
     * <code>int32 dodge_chance = 15;</code>
     */
    private $dodge_chance = 0;
    /**
     * <pre>
     *格挡几率
     * </pre>
     *
     * <code>int32 block_chance = 16;</code>
     */
    private $block_chance = 0;
    /**
     * <pre>
     *防御穿透几率
     * </pre>
     *
     * <code>int32 def_pentrate_p = 17;</code>
     */
    private $def_pentrate_p = 0;
    /**
     * <pre>
     * 命中几率
     * </pre>
     *
     * <code>int32 hit_chance = 18;</code>
     */
    private $hit_chance = 0;
    /**
     * <pre>
     *破击几率
     * </pre>
     *
     * <code>int32 block_pentrate_chance = 19;</code>
     */
    private $block_pentrate_chance = 0;
    /**
     * <pre>
     * 元素属性防御
     * </pre>
     *
     * <code>int32 mag_def3 = 20;</code>
     */
    private $mag_def3 = 0;
    /**
     * <pre>
     * 奥术属性防御
     * </pre>
     *
     * <code>int32 mag_def4 = 21;</code>
     */
    private $mag_def4 = 0;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 role_id = 1;</code>
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     * <code>int32 role_id = 1;</code>
     */
    public function setRoleId($var)
    {
        GPBUtil::checkInt32($var);
        $this->role_id = $var;
    }

    /**
     * <code>int32 gender = 2;</code>
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * <code>int32 gender = 2;</code>
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;
    }

    /**
     * <code>int32 level = 3;</code>
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * <code>int32 level = 3;</code>
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;
    }

    /**
     * <pre>
     *力量
     * </pre>
     *
     * <code>int32 strength = 4;</code>
     */
    public function getStrength()
    {
        return $this->strength;
    }

    /**
     * <pre>
     *力量
     * </pre>
     *
     * <code>int32 strength = 4;</code>
     */
    public function setStrength($var)
    {
        GPBUtil::checkInt32($var);
        $this->strength = $var;
    }

    /**
     * <pre>
     *敏捷
     * </pre>
     *
     * <code>int32 agile = 5;</code>
     */
    public function getAgile()
    {
        return $this->agile;
    }

    /**
     * <pre>
     *敏捷
     * </pre>
     *
     * <code>int32 agile = 5;</code>
     */
    public function setAgile($var)
    {
        GPBUtil::checkInt32($var);
        $this->agile = $var;
    }

    /**
     * <pre>
     * 智力
     * </pre>
     *
     * <code>int32 intelligence = 6;</code>
     */
    public function getIntelligence()
    {
        return $this->intelligence;
    }

    /**
     * <pre>
     * 智力
     * </pre>
     *
     * <code>int32 intelligence = 6;</code>
     */
    public function setIntelligence($var)
    {
        GPBUtil::checkInt32($var);
        $this->intelligence = $var;
    }

    /**
     * <pre>
     *体质
     * </pre>
     *
     * <code>int32 vit = 7;</code>
     */
    public function getVit()
    {
        return $this->vit;
    }

    /**
     * <pre>
     *体质
     * </pre>
     *
     * <code>int32 vit = 7;</code>
     */
    public function setVit($var)
    {
        GPBUtil::checkInt32($var);
        $this->vit = $var;
    }

    /**
     * <pre>
     *最大生命值
     * </pre>
     *
     * <code>int32 max_hp = 8;</code>
     */
    public function getMaxHp()
    {
        return $this->max_hp;
    }

    /**
     * <pre>
     *最大生命值
     * </pre>
     *
     * <code>int32 max_hp = 8;</code>
     */
    public function setMaxHp($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_hp = $var;
    }

    /**
     * <pre>
     *攻击力
     * </pre>
     *
     * <code>int32 atack = 9;</code>
     */
    public function getAtack()
    {
        return $this->atack;
    }

    /**
     * <pre>
     *攻击力
     * </pre>
     *
     * <code>int32 atack = 9;</code>
     */
    public function setAtack($var)
    {
        GPBUtil::checkInt32($var);
        $this->atack = $var;
    }

    /**
     * <pre>
     *防御力
     * </pre>
     *
     * <code>int32 def = 10;</code>
     */
    public function getDef()
    {
        return $this->def;
    }

    /**
     * <pre>
     *防御力
     * </pre>
     *
     * <code>int32 def = 10;</code>
     */
    public function setDef($var)
    {
        GPBUtil::checkInt32($var);
        $this->def = $var;
    }

    /**
     * <pre>
     * 神圣属性防御
     * </pre>
     *
     * <code>int32 mag_def1 = 11;</code>
     */
    public function getMagDef1()
    {
        return $this->mag_def1;
    }

    /**
     * <pre>
     * 神圣属性防御
     * </pre>
     *
     * <code>int32 mag_def1 = 11;</code>
     */
    public function setMagDef1($var)
    {
        GPBUtil::checkInt32($var);
        $this->mag_def1 = $var;
    }

    /**
     * <pre>
     *暗影属性防御
     * </pre>
     *
     * <code>int32 mag_def2 = 12;</code>
     */
    public function getMagDef2()
    {
        return $this->mag_def2;
    }

    /**
     * <pre>
     *暗影属性防御
     * </pre>
     *
     * <code>int32 mag_def2 = 12;</code>
     */
    public function setMagDef2($var)
    {
        GPBUtil::checkInt32($var);
        $this->mag_def2 = $var;
    }

    /**
     * <pre>
     *暴击几率
     * </pre>
     *
     * <code>int32 crit_chance = 13;</code>
     */
    public function getCritChance()
    {
        return $this->crit_chance;
    }

    /**
     * <pre>
     *暴击几率
     * </pre>
     *
     * <code>int32 crit_chance = 13;</code>
     */
    public function setCritChance($var)
    {
        GPBUtil::checkInt32($var);
        $this->crit_chance = $var;
    }

    /**
     * <pre>
     * 必杀伤害加成几率
     * </pre>
     *
     * <code>int32 slay_p = 14;</code>
     */
    public function getSlayP()
    {
        return $this->slay_p;
    }

    /**
     * <pre>
     * 必杀伤害加成几率
     * </pre>
     *
     * <code>int32 slay_p = 14;</code>
     */
    public function setSlayP($var)
    {
        GPBUtil::checkInt32($var);
        $this->slay_p = $var;
    }

    /**
     * <pre>
     *闪避几率
     * </pre>
     *
     * <code>int32 dodge_chance = 15;</code>
     */
    public function getDodgeChance()
    {
        return $this->dodge_chance;
    }

    /**
     * <pre>
     *闪避几率
     * </pre>
     *
     * <code>int32 dodge_chance = 15;</code>
     */
    public function setDodgeChance($var)
    {
        GPBUtil::checkInt32($var);
        $this->dodge_chance = $var;
    }

    /**
     * <pre>
     *格挡几率
     * </pre>
     *
     * <code>int32 block_chance = 16;</code>
     */
    public function getBlockChance()
    {
        return $this->block_chance;
    }

    /**
     * <pre>
     *格挡几率
     * </pre>
     *
     * <code>int32 block_chance = 16;</code>
     */
    public function setBlockChance($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_chance = $var;
    }

    /**
     * <pre>
     *防御穿透几率
     * </pre>
     *
     * <code>int32 def_pentrate_p = 17;</code>
     */
    public function getDefPentrateP()
    {
        return $this->def_pentrate_p;
    }

    /**
     * <pre>
     *防御穿透几率
     * </pre>
     *
     * <code>int32 def_pentrate_p = 17;</code>
     */
    public function setDefPentrateP($var)
    {
        GPBUtil::checkInt32($var);
        $this->def_pentrate_p = $var;
    }

    /**
     * <pre>
     * 命中几率
     * </pre>
     *
     * <code>int32 hit_chance = 18;</code>
     */
    public function getHitChance()
    {
        return $this->hit_chance;
    }

    /**
     * <pre>
     * 命中几率
     * </pre>
     *
     * <code>int32 hit_chance = 18;</code>
     */
    public function setHitChance($var)
    {
        GPBUtil::checkInt32($var);
        $this->hit_chance = $var;
    }

    /**
     * <pre>
     *破击几率
     * </pre>
     *
     * <code>int32 block_pentrate_chance = 19;</code>
     */
    public function getBlockPentrateChance()
    {
        return $this->block_pentrate_chance;
    }

    /**
     * <pre>
     *破击几率
     * </pre>
     *
     * <code>int32 block_pentrate_chance = 19;</code>
     */
    public function setBlockPentrateChance($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_pentrate_chance = $var;
    }

    /**
     * <pre>
     * 元素属性防御
     * </pre>
     *
     * <code>int32 mag_def3 = 20;</code>
     */
    public function getMagDef3()
    {
        return $this->mag_def3;
    }

    /**
     * <pre>
     * 元素属性防御
     * </pre>
     *
     * <code>int32 mag_def3 = 20;</code>
     */
    public function setMagDef3($var)
    {
        GPBUtil::checkInt32($var);
        $this->mag_def3 = $var;
    }

    /**
     * <pre>
     * 奥术属性防御
     * </pre>
     *
     * <code>int32 mag_def4 = 21;</code>
     */
    public function getMagDef4()
    {
        return $this->mag_def4;
    }

    /**
     * <pre>
     * 奥术属性防御
     * </pre>
     *
     * <code>int32 mag_def4 = 21;</code>
     */
    public function setMagDef4($var)
    {
        GPBUtil::checkInt32($var);
        $this->mag_def4 = $var;
    }

}

