<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 基本的用户信息
 * </pre>
 *
 * Protobuf type <code>proto.playerinfo.BasePlayerInfo</code>
 */
class BasePlayerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 player_id = 1;</code>
     */
    private $player_id = 0;
    /**
     * <pre>
     * 平台id
     * </pre>
     *
     * <code>int64 userid = 2;</code>
     */
    private $userid = 0;
    /**
     * <pre>
     * 分服id
     * </pre>
     *
     * <code>int32 sid = 3;</code>
     */
    private $sid = 0;
    /**
     * <pre>
     * 分服下角色index
     * </pre>
     *
     * <code>int32 index = 4;</code>
     */
    private $index = 0;
    /**
     * <code>string name = 5;</code>
     */
    private $name = '';
    /**
     * <code>int32 status = 6;</code>
     */
    private $status = 0;
    /**
     * <code>int32 profession = 7;</code>
     */
    private $profession = 0;
    /**
     * <code>int32 level = 8;</code>
     */
    private $level = 0;
    /**
     * <code>int32 max_level = 9;</code>
     */
    private $max_level = 0;
    /**
     * <code>int32 fashion_tid = 10;</code>
     */
    private $fashion_tid = 0;
    /**
     * <code>int32 weapon_tid = 11;</code>
     */
    private $weapon_tid = 0;
    /**
     * <code>int32 init_map_id = 12;</code>
     */
    private $init_map_id = 0;
    /**
     * <code>int32 init_map_x = 13;</code>
     */
    private $init_map_x = 0;
    /**
     * <code>int32 init_map_y = 14;</code>
     */
    private $init_map_y = 0;
    /**
     * <code>int32 init_map_z = 15;</code>
     */
    private $init_map_z = 0;
    /**
     * <code>int32 init_skill_1 = 16;</code>
     */
    private $init_skill_1 = 0;
    /**
     * <code>int32 init_skill_2 = 17;</code>
     */
    private $init_skill_2 = 0;
    /**
     * <code>int32 init_skill_3 = 18;</code>
     */
    private $init_skill_3 = 0;
    /**
     * <pre>
     *装备10个位置
     * </pre>
     *
     * <code>int32 equip_tid_1 = 19;</code>
     */
    private $equip_tid_1 = 0;
    /**
     * <code>int32 equip_tid_2 = 20;</code>
     */
    private $equip_tid_2 = 0;
    /**
     * <code>int32 equip_tid_3 = 21;</code>
     */
    private $equip_tid_3 = 0;
    /**
     * <code>int32 equip_tid_4 = 22;</code>
     */
    private $equip_tid_4 = 0;
    /**
     * <code>int32 equip_tid_5 = 23;</code>
     */
    private $equip_tid_5 = 0;
    /**
     * <code>int32 equip_tid_6 = 24;</code>
     */
    private $equip_tid_6 = 0;
    /**
     * <code>int32 equip_tid_7 = 25;</code>
     */
    private $equip_tid_7 = 0;
    /**
     * <code>int32 equip_tid_8 = 26;</code>
     */
    private $equip_tid_8 = 0;
    /**
     * <code>int32 equip_tid_9 = 27;</code>
     */
    private $equip_tid_9 = 0;
    /**
     * <code>int32 equip_tid_10 = 28;</code>
     */
    private $equip_tid_10 = 0;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 player_id = 1;</code>
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * <code>int64 player_id = 1;</code>
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->player_id = $var;
    }

    /**
     * <pre>
     * 平台id
     * </pre>
     *
     * <code>int64 userid = 2;</code>
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * <pre>
     * 平台id
     * </pre>
     *
     * <code>int64 userid = 2;</code>
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;
    }

    /**
     * <pre>
     * 分服id
     * </pre>
     *
     * <code>int32 sid = 3;</code>
     */
    public function getSid()
    {
        return $this->sid;
    }

    /**
     * <pre>
     * 分服id
     * </pre>
     *
     * <code>int32 sid = 3;</code>
     */
    public function setSid($var)
    {
        GPBUtil::checkInt32($var);
        $this->sid = $var;
    }

    /**
     * <pre>
     * 分服下角色index
     * </pre>
     *
     * <code>int32 index = 4;</code>
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * <pre>
     * 分服下角色index
     * </pre>
     *
     * <code>int32 index = 4;</code>
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;
    }

    /**
     * <code>string name = 5;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 5;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>int32 status = 6;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>int32 status = 6;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;
    }

    /**
     * <code>int32 profession = 7;</code>
     */
    public function getProfession()
    {
        return $this->profession;
    }

    /**
     * <code>int32 profession = 7;</code>
     */
    public function setProfession($var)
    {
        GPBUtil::checkInt32($var);
        $this->profession = $var;
    }

    /**
     * <code>int32 level = 8;</code>
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * <code>int32 level = 8;</code>
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;
    }

    /**
     * <code>int32 max_level = 9;</code>
     */
    public function getMaxLevel()
    {
        return $this->max_level;
    }

    /**
     * <code>int32 max_level = 9;</code>
     */
    public function setMaxLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_level = $var;
    }

    /**
     * <code>int32 fashion_tid = 10;</code>
     */
    public function getFashionTid()
    {
        return $this->fashion_tid;
    }

    /**
     * <code>int32 fashion_tid = 10;</code>
     */
    public function setFashionTid($var)
    {
        GPBUtil::checkInt32($var);
        $this->fashion_tid = $var;
    }

    /**
     * <code>int32 weapon_tid = 11;</code>
     */
    public function getWeaponTid()
    {
        return $this->weapon_tid;
    }

    /**
     * <code>int32 weapon_tid = 11;</code>
     */
    public function setWeaponTid($var)
    {
        GPBUtil::checkInt32($var);
        $this->weapon_tid = $var;
    }

    /**
     * <code>int32 init_map_id = 12;</code>
     */
    public function getInitMapId()
    {
        return $this->init_map_id;
    }

    /**
     * <code>int32 init_map_id = 12;</code>
     */
    public function setInitMapId($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_id = $var;
    }

    /**
     * <code>int32 init_map_x = 13;</code>
     */
    public function getInitMapX()
    {
        return $this->init_map_x;
    }

    /**
     * <code>int32 init_map_x = 13;</code>
     */
    public function setInitMapX($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_x = $var;
    }

    /**
     * <code>int32 init_map_y = 14;</code>
     */
    public function getInitMapY()
    {
        return $this->init_map_y;
    }

    /**
     * <code>int32 init_map_y = 14;</code>
     */
    public function setInitMapY($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_y = $var;
    }

    /**
     * <code>int32 init_map_z = 15;</code>
     */
    public function getInitMapZ()
    {
        return $this->init_map_z;
    }

    /**
     * <code>int32 init_map_z = 15;</code>
     */
    public function setInitMapZ($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_z = $var;
    }

    /**
     * <code>int32 init_skill_1 = 16;</code>
     */
    public function getInitSkill1()
    {
        return $this->init_skill_1;
    }

    /**
     * <code>int32 init_skill_1 = 16;</code>
     */
    public function setInitSkill1($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_skill_1 = $var;
    }

    /**
     * <code>int32 init_skill_2 = 17;</code>
     */
    public function getInitSkill2()
    {
        return $this->init_skill_2;
    }

    /**
     * <code>int32 init_skill_2 = 17;</code>
     */
    public function setInitSkill2($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_skill_2 = $var;
    }

    /**
     * <code>int32 init_skill_3 = 18;</code>
     */
    public function getInitSkill3()
    {
        return $this->init_skill_3;
    }

    /**
     * <code>int32 init_skill_3 = 18;</code>
     */
    public function setInitSkill3($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_skill_3 = $var;
    }

    /**
     * <pre>
     *装备10个位置
     * </pre>
     *
     * <code>int32 equip_tid_1 = 19;</code>
     */
    public function getEquipTid1()
    {
        return $this->equip_tid_1;
    }

    /**
     * <pre>
     *装备10个位置
     * </pre>
     *
     * <code>int32 equip_tid_1 = 19;</code>
     */
    public function setEquipTid1($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_1 = $var;
    }

    /**
     * <code>int32 equip_tid_2 = 20;</code>
     */
    public function getEquipTid2()
    {
        return $this->equip_tid_2;
    }

    /**
     * <code>int32 equip_tid_2 = 20;</code>
     */
    public function setEquipTid2($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_2 = $var;
    }

    /**
     * <code>int32 equip_tid_3 = 21;</code>
     */
    public function getEquipTid3()
    {
        return $this->equip_tid_3;
    }

    /**
     * <code>int32 equip_tid_3 = 21;</code>
     */
    public function setEquipTid3($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_3 = $var;
    }

    /**
     * <code>int32 equip_tid_4 = 22;</code>
     */
    public function getEquipTid4()
    {
        return $this->equip_tid_4;
    }

    /**
     * <code>int32 equip_tid_4 = 22;</code>
     */
    public function setEquipTid4($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_4 = $var;
    }

    /**
     * <code>int32 equip_tid_5 = 23;</code>
     */
    public function getEquipTid5()
    {
        return $this->equip_tid_5;
    }

    /**
     * <code>int32 equip_tid_5 = 23;</code>
     */
    public function setEquipTid5($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_5 = $var;
    }

    /**
     * <code>int32 equip_tid_6 = 24;</code>
     */
    public function getEquipTid6()
    {
        return $this->equip_tid_6;
    }

    /**
     * <code>int32 equip_tid_6 = 24;</code>
     */
    public function setEquipTid6($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_6 = $var;
    }

    /**
     * <code>int32 equip_tid_7 = 25;</code>
     */
    public function getEquipTid7()
    {
        return $this->equip_tid_7;
    }

    /**
     * <code>int32 equip_tid_7 = 25;</code>
     */
    public function setEquipTid7($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_7 = $var;
    }

    /**
     * <code>int32 equip_tid_8 = 26;</code>
     */
    public function getEquipTid8()
    {
        return $this->equip_tid_8;
    }

    /**
     * <code>int32 equip_tid_8 = 26;</code>
     */
    public function setEquipTid8($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_8 = $var;
    }

    /**
     * <code>int32 equip_tid_9 = 27;</code>
     */
    public function getEquipTid9()
    {
        return $this->equip_tid_9;
    }

    /**
     * <code>int32 equip_tid_9 = 27;</code>
     */
    public function setEquipTid9($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_9 = $var;
    }

    /**
     * <code>int32 equip_tid_10 = 28;</code>
     */
    public function getEquipTid10()
    {
        return $this->equip_tid_10;
    }

    /**
     * <code>int32 equip_tid_10 = 28;</code>
     */
    public function setEquipTid10($var)
    {
        GPBUtil::checkInt32($var);
        $this->equip_tid_10 = $var;
    }

}

