<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.playerinfo.CreatePlayerRequest</code>
 */
class CreatePlayerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     *1男 2女，0未设置
     * </pre>
     *
     * <code>int32 gender = 2;</code>
     */
    private $gender = 0;
    /**
     * <code>int32 profession = 3;</code>
     */
    private $profession = 0;
    /**
     * <code>int32 index = 4;</code>
     */
    private $index = 0;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     *1男 2女，0未设置
     * </pre>
     *
     * <code>int32 gender = 2;</code>
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * <pre>
     *1男 2女，0未设置
     * </pre>
     *
     * <code>int32 gender = 2;</code>
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;
    }

    /**
     * <code>int32 profession = 3;</code>
     */
    public function getProfession()
    {
        return $this->profession;
    }

    /**
     * <code>int32 profession = 3;</code>
     */
    public function setProfession($var)
    {
        GPBUtil::checkInt32($var);
        $this->profession = $var;
    }

    /**
     * <code>int32 index = 4;</code>
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * <code>int32 index = 4;</code>
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;
    }

}

