<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 初始化的角色属性
 * </pre>
 *
 * Protobuf type <code>proto.playerinfo.InitPlayInfo</code>
 */
class InitPlayInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.proto.playerinfo.BasePlayAttribute attribute = 1;</code>
     */
    private $attribute = null;
    /**
     * <code>int32 max_level = 2;</code>
     */
    private $max_level = 0;
    /**
     * <code>int32 init_map_id = 3;</code>
     */
    private $init_map_id = 0;
    /**
     * <code>int32 init_map_x = 4;</code>
     */
    private $init_map_x = 0;
    /**
     * <code>int32 init_map_y = 5;</code>
     */
    private $init_map_y = 0;
    /**
     * <code>int32 init_map_z = 6;</code>
     */
    private $init_map_z = 0;
    /**
     * <code>int32 init_skill_1 = 7;</code>
     */
    private $init_skill_1 = 0;
    /**
     * <code>int32 init_skill_2 = 8;</code>
     */
    private $init_skill_2 = 0;
    /**
     * <code>int32 init_skill_3 = 9;</code>
     */
    private $init_skill_3 = 0;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>.proto.playerinfo.BasePlayAttribute attribute = 1;</code>
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * <code>.proto.playerinfo.BasePlayAttribute attribute = 1;</code>
     */
    public function setAttribute(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Playerinfo\BasePlayAttribute::class);
        $this->attribute = $var;
    }

    /**
     * <code>int32 max_level = 2;</code>
     */
    public function getMaxLevel()
    {
        return $this->max_level;
    }

    /**
     * <code>int32 max_level = 2;</code>
     */
    public function setMaxLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_level = $var;
    }

    /**
     * <code>int32 init_map_id = 3;</code>
     */
    public function getInitMapId()
    {
        return $this->init_map_id;
    }

    /**
     * <code>int32 init_map_id = 3;</code>
     */
    public function setInitMapId($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_id = $var;
    }

    /**
     * <code>int32 init_map_x = 4;</code>
     */
    public function getInitMapX()
    {
        return $this->init_map_x;
    }

    /**
     * <code>int32 init_map_x = 4;</code>
     */
    public function setInitMapX($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_x = $var;
    }

    /**
     * <code>int32 init_map_y = 5;</code>
     */
    public function getInitMapY()
    {
        return $this->init_map_y;
    }

    /**
     * <code>int32 init_map_y = 5;</code>
     */
    public function setInitMapY($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_y = $var;
    }

    /**
     * <code>int32 init_map_z = 6;</code>
     */
    public function getInitMapZ()
    {
        return $this->init_map_z;
    }

    /**
     * <code>int32 init_map_z = 6;</code>
     */
    public function setInitMapZ($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_map_z = $var;
    }

    /**
     * <code>int32 init_skill_1 = 7;</code>
     */
    public function getInitSkill1()
    {
        return $this->init_skill_1;
    }

    /**
     * <code>int32 init_skill_1 = 7;</code>
     */
    public function setInitSkill1($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_skill_1 = $var;
    }

    /**
     * <code>int32 init_skill_2 = 8;</code>
     */
    public function getInitSkill2()
    {
        return $this->init_skill_2;
    }

    /**
     * <code>int32 init_skill_2 = 8;</code>
     */
    public function setInitSkill2($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_skill_2 = $var;
    }

    /**
     * <code>int32 init_skill_3 = 9;</code>
     */
    public function getInitSkill3()
    {
        return $this->init_skill_3;
    }

    /**
     * <code>int32 init_skill_3 = 9;</code>
     */
    public function setInitSkill3($var)
    {
        GPBUtil::checkInt32($var);
        $this->init_skill_3 = $var;
    }

}

