<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.playerinfo.PlayerLoginRequest</code>
 */
class PlayerLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 player_id = 1;</code>
     */
    private $player_id = 0;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 player_id = 1;</code>
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * <code>int64 player_id = 1;</code>
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->player_id = $var;
    }

}

