<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.playerinfo.PlayerInfo</code>
 */
class PlayerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.proto.playerinfo.BasePlayerInfo baseinfo = 1;</code>
     */
    private $baseinfo = null;
    /**
     * <code>.proto.playerinfo.BasePlayAttribute baseAttribute = 2;</code>
     */
    private $baseAttribute = null;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>.proto.playerinfo.BasePlayerInfo baseinfo = 1;</code>
     */
    public function getBaseinfo()
    {
        return $this->baseinfo;
    }

    /**
     * <code>.proto.playerinfo.BasePlayerInfo baseinfo = 1;</code>
     */
    public function setBaseinfo(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Playerinfo\BasePlayerInfo::class);
        $this->baseinfo = $var;
    }

    /**
     * <code>.proto.playerinfo.BasePlayAttribute baseAttribute = 2;</code>
     */
    public function getBaseAttribute()
    {
        return $this->baseAttribute;
    }

    /**
     * <code>.proto.playerinfo.BasePlayAttribute baseAttribute = 2;</code>
     */
    public function setBaseAttribute(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Playerinfo\BasePlayAttribute::class);
        $this->baseAttribute = $var;
    }

}

