<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerinfo.proto

namespace Proto\Playerinfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>proto.playerinfo.PlayerLoginResponse</code>
 */
class PlayerLoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.proto.playerinfo.PlayerInfo player = 1;</code>
     */
    private $player = null;

    public function __construct() {
        \GPBMetadata\Playerinfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>.proto.playerinfo.PlayerInfo player = 1;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <code>.proto.playerinfo.PlayerInfo player = 1;</code>
     */
    public function setPlayer(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Playerinfo\PlayerInfo::class);
        $this->player = $var;
    }

}

