<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace GPBMetadata;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Playerinfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6010a0d6163636f756e742e70726f746f120d70726f746f2e6163636f" .
            "756e741a10706c61796572696e666f2e70726f746f22560a134163636f75" .
            "6e744c6f67696e52657175657374120e0a066f70656e6964180120012803" .
            "120d0a05746f6b656e180220012809120b0a037369641803200128051213" .
            "0a0b636c69656e745f7479706518042001280522640a144163636f756e74" .
            "4c6f67696e526573706f6e7365120e0a066f70656e696418012001280312" .
            "0b0a03736964180220012805122f0a05726f6c657318032003280b32202e" .
            "70726f746f2e706c61796572696e666f2e42617365506c61796572496e66" .
            "6f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

